scoutapp/scout_apm_python

- src/scout_apm/api/context.py
- src/scout_apm/django/instruments/view.py
Start the work on #2.
The django instrumentation part needs testing and refinement across various versions.
> Request context

- src/scout_apm/flask/__init__.py
> Doesn't continue the request if is an options request

- src/scout_apm/core/config/config.py
- src/scout_apm/core/git_revision.py
- src/scout_apm/core/metadata.py
- tests/scout_apm_tests/git_revision_test.py
Enable deploy tracking by detecting Git SHA via explicit config or Env vars
> Detect Git Sha from Env or Config

- src/scout_apm/core/tracked_request.py
- tests/scout_apm_tests/tracked_request_test.py
Resolves https://github.com/scoutapp/scout_apm_python/issues/88
> Do not collect backtraces in Controller or Middleware

- .travis.yml
- CHANGELOG.md
- setup.cfg
- setup.py
- src/scout_apm/core/__init__.py
- src/scout_apm/core/ext/objtrace.c
- src/scout_apm/core/samplers/memory.py
- src/scout_apm/core/tracked_request.py
- tests/scout_apm_tests/api/instrument_test.py
- tests/scout_apm_tests/commands_test.py
- tests/scout_apm_tests/objtrace_test.py
- tests/scout_apm_tests/tracked_request_test.py
v1.3.0.
Implements object allocation tracing via extension module.
Reports the memory delta in MB for Tracked Requests.
> v1.3.0. Object allocation tracing, Mem Delta for Tracked Requests

- src/scout_apm/core/socket.py
This appears to fix the socket timeout errors in #125.
Previously we were simply ignoring the contents of any response message
from the core agent, not even reading off the socket. We were seeing
`timed out` exceptions. By reading off the socket every time, and fixing
the `recv` calls to actually read *all* of the data off the socket, the
timeouts go away on my system.
> Always read the response to CoreAgent messages

- src/scout_apm/instruments/redis.py
This accounts for breaking changes in this commit: https://github.com/andymccurdy/redis-py/commit/fad791c894c5d52921b4e449e1ba05133de5b2ec
> Add compatibility with redis-py 3.

- setup.cfg
- tests/integration/app.py
Add a WSGI application for manual testing.
> Add a WSGI application for manual testing.

- src/scout_apm/api/__init__.py
- tests/integration/test_api.py
This is mainly useful for Python 2.7 users that use a language other than English and don't take advantage of Python's unicode support — hopefully a small group of users.
> Accept non-ASCII bytestrings in public APIs.

- tests/integration/instruments/test_elasticsearch.py
> Fix code style for elasticsearch tests

- tests/integration/test_django.py
Rename the middleware version decorators to be a bit more explicit, and make the `finish_tracked_request_if_old_style_middlware` fixture 'autouse' so it doesn't need repeating in each test.
> Tidy Django tests

- README.md
Changed URL to https://www.scoutapm.com from https://www.scoutapp.com for consistency sake.
> Updating README.md with correct URL for website

- src/scout_apm/core/monkey.py
Remove the pieces copy-pasted from ProxyTypes that we aren't using, as per the comment to do so.
> Simplify Monkey module

- CHANGELOG.md
- src/scout_apm/compat.py
- src/scout_apm/core/tracked_request.py
- src/scout_apm/core/util.py
- src/scout_apm/django/middleware.py
- tests/integration/django_app.py
- tests/integration/test_django.py
- tests/unit/core/test_util.py
> Implement request queue timing in Django

- src/scout_apm/core/core_agent_manager.py
- tests/integration/core/test_core_agent_manager.py
Also improve the assertions made to check for the right log messages.
> Use Pytest caplog for log record test assertions

- tests/integration/test_django.py
- tests/integration/test_flask.py
This gets Flask's test coverage to 100%.
> Test ignore functionality on Flask

- CHANGELOG.md
To help everyone follow. The numbers were added previously without links, and I forgot to add them. Will be more diligent in the future.
> Add PR links to CHANGELOG for pending version

- CHANGELOG.md
- src/scout_apm/django/instruments/sql.py
- src/scout_apm/django/middleware.py
> Use Django 2.0+ database instrumentation

- CHANGELOG.md
- README.md
- src/scout_apm/dramatiq.py
- tests/integration/test_celery.py
- tests/integration/test_dramatiq.py
- tox.ini
> Add Dramatiq integration

- src/scout_apm/core/config.py
- tests/unit/core/test_config.py
Similar to #224, turn these one method classes into plain functions, as per Aymeric's recommendations. This is slightly faster and clearer.
> Flatten config conversion classes into functions

- CHANGELOG.md
- src/scout_apm/celery.py
- tests/integration/test_celery.py
> Track Celery task ID and parent task ID

- CHANGELOG.md
- README.md
- pytest.ini
- src/scout_apm/nameko.py
- tests/integration/test_nameko.py
- tox.ini
> Add Nameko integration

- src/scout_apm/core/commands.py
- src/scout_apm/core/metadata.py
- src/scout_apm/core/samplers/__init__.py
- tests/unit/core/test_commands.py
Rework the initializer for `ApplicationEvent` so that it needs all the arguments to be constructed.
> Refactor ApplicationEvent

- CHANGELOG.md
- src/scout_apm/core/commands.py
- src/scout_apm/core/config.py
- src/scout_apm/core/socket.py
- tests/unit/core/test_commands.py
See: https://github.com/scoutapp/scout_apm_python/issues/248
This also requires the binary agent changes, so do not merge yet.
> Override hostname

- src/scout_apm/core/metadata.py
- src/scout_apm/core/samplers/__init__.py
- src/scout_apm/core/samplers/cpu.py
- src/scout_apm/core/tracked_request.py
- tests/unit/core/test_commands.py
- tests/unit/core/test_tracked_request.py
Use this slightly clearer import pattern
> import datetime as dt

- src/scout_apm/core/config.py
- src/scout_apm/core/web_requests.py
- tests/unit/core/test_web_requests.py
> Add uri_reporting setting

- CHANGELOG.md
Final step for #249 before release.
> Add CHANGELOG message for query parameter capture

- tests/unit/core/samplers/test_memory.py
- tox.ini
Had this on my machine for the first time today, guess I'm using enough memory right now to go over the int/long divide.
> Fix Python 2 int/long test failure

- setup.py
These links appear on the sidebar on PyPI and help surface relevant places to go to users.
> Add project_urls links

- CHANGELOG.md
- src/scout_apm/core/core_agent_manager.py
- tests/integration/core/test_core_agent_manager.py
> Improve deprecated log_level warning message

- tests/integration/test_falcon.py
As per comments, we weren't really testing crashing, but Falcon's internal error responses. This improves the tests to cover both cases.
> Add Falcon crash test

- CHANGELOG.md
- src/scout_apm/pyramid.py
- tests/integration/test_pyramid.py
> Track errors on Pyramid

- src/scout_apm/core/__init__.py
- tests/unit/test_core.py
Fixes #100. Currently Windows is not supported.
> Prevent starting on Windows

- tests/unit/core/test_objtrace.py
Ensure key pathways in the C level extension get tested.
> Improve objtrace tests

- tests/integration/instruments/test_elasticsearch.py
- tests/integration/instruments/test_jinja2.py
- tests/integration/instruments/test_pymongo.py
- tests/integration/instruments/test_redis.py
- tests/integration/instruments/test_urllib3.py
- tests/tools.py
- tests/unit/core/test_metadata.py
Copy this out of #302 and use it everywhere in tests that we had the functionality written out "long hand."
> Add pretend_package_unavailable test tool

- setup.cfg
- tests/integration/core/test_socket.py
- tests/integration/test_flask_sqlalchemy.py
- tox.ini
Add my two flake8 plugins, and ban relative imports (only two instances to rewrite)
> Install my flake8 plugins

- CHANGELOG.md
- setup.py
- src/scout_apm/compat.py
- src/scout_apm/core/__init__.py
It's a small library so no point adding a dependency right now I think.
> Merge in kwargs-only

- src/scout_apm/core/socket.py
A few bits of tidy up post #322.
> Tidy CoreAgentSocket

- src/scout_apm/core/metadata.py
> Add language_version to metadata

- CHANGELOG.md
- src/scout_apm/compat.py
- src/scout_apm/django/middleware.py
- tests/integration/django_app.py
- tests/integration/test_django.py
- tests/tools.py
- tox.ini
> Capture tastypie resource name in method

- CHANGELOG.md
- src/scout_apm/sqlalchemy.py
- tests/integration/test_sqlalchemy.py
> Track SQL Alchemy executemany calls as multi-queries

- src/scout_apm/async_/starlette.py
- tests/integration/test_starlette_py36plus.py
> Instrument Starlette background tasks

- src/scout_apm/instruments/elasticsearch.py
- src/scout_apm/instruments/pymongo.py
- tests/integration/instruments/test_elasticsearch.py
- tests/integration/instruments/test_pymongo.py
> Remove exec from PyMongo instrument

- tests/integration/django_app.py
It's shorter and simpler to read.
> Use wrapt for decorator in Django tests

- src/scout_apm/bottle.py
Should have been done as part of #311. Defining the decorator as an outer function also provides a small performance improvement.
> Convert Bottle decorator to wrapt

- src/scout_apm/async_/starlette.py
- tests/integration/test_starlette_py36plus.py
> Support Starlette authentication

- CHANGELOG.md
- README.md
- src/scout_apm/huey.py
- tests/integration/test_huey.py
- tox.ini
> Add Huey integration

- requirements.txt
- setup.cfg
This file isn't used anywhere.
> Remove unused requirements.txt

- CHANGELOG.md
- README.md
- src/scout_apm/rq.py
- tests/integration/test_rq.py
- tox.ini
> Instrument RQ

- src/scout_apm/django/middleware.py
- tests/integration/django_app.py
- tests/integration/test_django.py
> Tag Django 5XX responses as errors

- src/scout_apm/bottle.py
- tests/integration/test_bottle.py
> Tag Bottle 5XX responses as errors

- CHANGELOG.md
- src/scout_apm/django/middleware.py
- tests/integration/django_app.py
- tests/integration/test_django.py
- tox.ini
> Improve Django Rest Framework ViewSet transaction names

- src/scout_apm/nameko.py
- tests/integration/test_nameko.py
> Tag Nameko 5XX responses as errors

- src/scout_apm/pyramid.py
- tests/integration/test_pyramid.py
> Tag Pyramid 5XX responses as errors

- src/scout_apm/async_/starlette.py
- tests/integration/test_starlette_py36plus.py
> Tag Starlette 5XX responses as errors

- src/scout_apm/rq.py
Accidentally committed in #375.
> Remove development comments from RQ integration

- tests/conftest.py
- tests/integration/core/test_core_agent_manager.py
- tests/integration/core/test_socket.py
This is used in multiple files so can live in the root conftest.
> Hoist shared fixture core_agent_manager

- tests/integration/test_starlette_py36plus.py
Fixes #363. On the issue I wrote about keeping some tests with the old format but I don't think it's worth it right now since Starlette promises backwards compatibility.
> Update Starlette tests for 0.13+

- CHANGELOG.md
- src/scout_apm/cherrypy.py
- src/scout_apm/compat.py
- src/scout_apm/core/web_requests.py
- tests/integration/test_cherrypy.py
- tox.ini
> Add CherryPy integration

- tests/integration/test_starlette_py36plus.py
Starlette docs don't cover it much, but I just discovered it's possible to use synchronous functions for endpoints. Test that we work with them.
> Test Starlette's synchronous endpoints

- tests/integration/instruments/test_elasticsearch.py
> xfail Elasticsearch positional argument test

- CHANGELOG.md
- src/scout_apm/instruments/jinja2.py
- tests/integration/instruments/test_jinja2.py
- tests/integration/instruments/test_jinja2_py36plus.py
> Fix Jinja2 async integration for Jinja2 2.11.0+

- src/scout_apm/falcon.py
> Remove unnecessary Hug import

- src/scout_apm/compat.py
- src/scout_apm/instruments/elasticsearch.py
- tests/unit/test_compat.py
Refactor this code added in #466 and test it separately.
> Extract decorator unwrapping to a separate function

- .travis.yml
As per https://pyfound.blogspot.com/2020/01/start-using-2fa-and-api-tokens-on-pypi.html .
> Move to PyPI API token

- src/scout_apm/core/socket.py
Should increase throughput a little bit.
> Use a single socket.sendall() in CoreAgentSocketThread

- src/scout_apm/core/web_requests.py
> Make ambiguous datetime cutoff epoch dynamic

- CHANGELOG.md
- src/scout_apm/core/core_agent_manager.py
- tests/integration/core/test_core_agent_manager.py
> Remove SCOUT_LOG_LEVEL deprecation warning

- CHANGELOG.md
- src/scout_apm/celery.py
- tests/compat.py
- tests/integration/test_celery.py
> Copy configuration from Celery app

- src/scout_apm/compat.py
- src/scout_apm/core/commands.py
Slight efficiency improvement.
> Use dict.items() in BatchCommand.from_tracked_request

- CHANGELOG.md
- src/scout_apm/core/tracked_request.py
- tests/unit/core/test_tracked_request.py
> Implement max span limit

- CHANGELOG.md
- src/scout_apm/core/__init__.py
- src/scout_apm/core/config.py
- tests/unit/test_core.py
> Allow disabling the shutdown message

- CHANGELOG.md
A little improvement of full stops, links, etc. for recent releases.
> Tidy changelog notes

- CHANGELOG.md
- src/scout_apm/core/config.py
- src/scout_apm/core/core_agent_manager.py
- src/scout_apm/core/socket.py
- tests/conftest.py
- tests/integration/core/test_core_agent_manager.py
- tests/unit/core/test_config.py
> Rename and alias some core agent config variables

- CHANGELOG.md
- src/scout_apm/django/apps.py
- tests/integration/test_django.py
> Support Django's BASE_DIR being a pathlib.Path

- CHANGELOG.md
- src/scout_apm/core/core_agent_manager.py
> Prevent core agent output at startup

- src/scout_apm/core/config.py
> Update core_agent_version to 1.2.9

- CHANGELOG.md
- src/scout_apm/core/metadata.py
- tests/unit/core/test_metadata.py
> Fix crash when scanning packages with incomplete metadata

- CHANGELOG.md
- src/scout_apm/core/commands.py
- src/scout_apm/core/config.py
- tests/unit/core/test_commands.py
- tests/unit/core/test_config.py
> Don't log Scout key during startup

- CHANGELOG.md
- src/scout_apm/rq.py
> Add HerokuWorker class to RQ integration

- CHANGELOG.md
- src/scout_apm/bottle.py
- src/scout_apm/cherrypy.py
- src/scout_apm/core/config.py
- src/scout_apm/core/web_requests.py
- src/scout_apm/django/middleware.py
- src/scout_apm/falcon.py
- src/scout_apm/pyramid.py
- tests/integration/test_bottle.py
- tests/integration/test_cherrypy.py
- tests/integration/test_django.py
- tests/integration/test_falcon.py
- tests/integration/test_flask.py
- tests/integration/test_nameko.py
- tests/integration/test_pyramid.py
- tests/integration/test_starlette_py36plus.py
> Add 'collect_remote_ip' setting

- .github/workflows/main.yml
- .pre-commit-config.yaml
- .travis.yml
- DEVELOPMENT.md
- tox.ini
> Test with GitHub Actions

- MANIFEST.in
- tox.ini
Using newer prune/graft/global-exclude keywords
> Improve MANIFEST.in declaration

- .github/workflows/main.yml
Run all the Python versions to the end.
> Don't fail fast on GitHub Actions CI

- tox.ini
This activates building the package with the pep517 backend and checking that configuration.
> Use isolated_build on tox

- README.md
> Update README CI link to GitHub Actions

- src/scout_apm/sqlalchemy.py
Picked from c46c79523358f88180caac77be8c5761e6482bba.
> Comment about SQLAlchemy flag

- setup.cfg
- src/scout_apm/django/middleware.py
- tests/tools.py
- tox.ini
This will help guard against bad inspection of the current Python version.
https://github.com/asottile/flake8-2020
> Install flake8-2020

- .pre-commit-config.yaml
- src/scout_apm/core/_objtrace.c
Enforce some more options on the repo.
https://github.com/pre-commit/pre-commit-hooks
> Add pre-commit-hooks for extra checks on code

- src/scout_apm/core/config.py
- src/scout_apm/core/core_agent_manager.py
- src/scout_apm/core/socket.py
- tests/unit/core/test_config.py
- tests/unit/core/test_core_agent_manager.py
> Extract derivation of socket path into shared function

- src/scout_apm/async_/instruments/jinja2.py
- src/scout_apm/async_/starlette.py
- src/scout_apm/bottle.py
- src/scout_apm/core/stacktracer.py
- src/scout_apm/core/tracked_request.py
- src/scout_apm/django/middleware.py
- src/scout_apm/flask/__init__.py
- src/scout_apm/instruments/elasticsearch.py
- src/scout_apm/instruments/jinja2.py
- src/scout_apm/instruments/pymongo.py
- src/scout_apm/instruments/redis.py
- src/scout_apm/instruments/urllib3.py
- src/scout_apm/pyramid.py
- src/scout_apm/rq.py
- tests/unit/core/test_tracked_request.py
Fixes #557. Reduces duplication.
> Add TrackedRequest.span() context manager

- CHANGELOG.md
- src/scout_apm/core/web_requests.py
- tests/unit/core/test_web_requests.py
Fixes a broken application reported on Slack.
> Add a cast to string of query parameters

- CHANGELOG.md
- src/scout_apm/core/platform_detection.py
- tests/unit/core/test_platform_detection.py
> Default to musl core agent on Linux

- tests/conftest.py
> Update pytest setup for Celery 5

- .github/workflows/main.yml
- CHANGELOG.md
- setup.py
- tests/compat.py
- tests/integration/django_app.py
- tox.ini
> Support Python 3.9

- setup.py
Undo hack from 3370a60c40041159b4fa01a9e1419d1a9be852c5
> Reactivate extensions

- CHANGELOG.md
- src/scout_apm/async_/starlette.py
- tests/integration/test_starlette_py36plus.py
> Handle ASGI apps in Starlette integration that are class instances

- DEVELOPMENT.md
* Note about scout-test-apps
* Cover release process
* Note about changing the Scout documentation
> Improve development documentation

- CHANGELOG.md
- src/scout_apm/core/backtrace.py
- tests/unit/core/test_backtrace.py
- tox.ini
> Exclude python library paths from the backtrace.

- CHANGELOG.md
- src/scout_apm/core/tracked_request.py
- tests/unit/core/test_tracked_request.py
> Change max spans reached log level to debug.

- CHANGELOG.md
- src/scout_apm/celery.py
- tests/integration/test_celery.py
> Track when exceptions occur in Celery on TrackedRequest.

- CHANGELOG.md
- src/scout_apm/instruments/elasticsearch.py
> Instrument terms_enum that was added in elasticsearch 7.14

- CHANGELOG.md
- src/scout_apm/instruments/jinja2.py
- tests/integration/instruments/test_jinja2_py36plus.py
- tox.ini
> Instrument Jinja v3 render_async.

- CHANGELOG.md
- src/scout_apm/core/context.py
- src/scout_apm/core/tracked_request.py
- tests/compat.py
- tests/conftest.py
- tests/integration/instruments/test_asyncio_py36plus.py
- tests/tools.py
- tests/unit/core/test_tracked_request.py
> Define TrackedRequest ContextVar at module level.

- src/scout_apm/core/_objtrace.c
This does not convert the thread specific counters into module
state structs.
References #661
> Convert objtrace to use PEP 489 multi-phase initialization.

- CHANGELOG.md
- src/scout_apm/celery.py
> Disconnect receiver from celery task_failure signal.

- .github/workflows/main.yml
- .github/workflows/release.yml
- CHANGELOG.md
> Split github main action to use ubuntu 18 and 20.

- CHANGELOG.md
- src/scout_apm/core/config.py
- src/scout_apm/core/platform_detection.py
- tests/unit/core/test_platform_detection.py
Default to latest v1.3.1 core agent version.
Closes #683
> Support ARM 64 architecture for core agent.

- .github/workflows/main.yml
- .github/workflows/release.yml
- CHANGELOG.md
This reverts commit 4c5b2f99a99202c3d73e52b243a3039ff95e8322.
Reverts #681
> Revert "Split github main action to use ubuntu 18 and 20. (#681)"

- CHANGELOG.md
- src/scout_apm/core/config.py
> Set core agent default version to v1.4.0

- CHANGELOG.md
- src/scout_apm/instruments/elasticsearch.py
> Wrap the import of elasticsearch for versioning in a try/except

- .pre-commit-config.yaml
- pyproject.toml
- src/scout_apm/celery.py
- src/scout_apm/core/backtrace.py
- src/scout_apm/core/config.py
- src/scout_apm/core/threading.py
- src/scout_apm/django/instruments/sql.py
- src/scout_apm/falcon.py
- Bumps versions to fix `pre-commit` scripts running. 
- Add [tool.poetry] section to `pyproject.toml` to facilitate using poetry venv.
- Fixing some linting errors and runs 3.11 linting on codebase.
> 756 development tooling updates

- README.md
- setup.py
- Bumps version to 3.0.1 
- removes broken screenshot link in readme
> bump version to 3.0.1 and remove broken image link

- .github/workflows/release.yml
- CHANGELOG.md
- setup.py
Bump version, update changelog
> Prepare for 3.4.0 release
