src/scout_apm/core/socket.py
src/scout_apm/flask/__init__.py
src/scout_apm/flask/sqlalchemy.py
src/scout_apm/sqlalchemy/__init__.py

This is a WIP still, but it works in my test env (flask 0.12.2) with a trivial app.
Once finished, will close #5 
```python
from flask import Flask
from scout_apm.flask import ScoutApm
app = Flask(__name__)
ScoutApm(app)
app.config['SCOUT_MONITOR'] = True
app.config['SCOUT_KEY'] = 'xxx'
app.config['SCOUT_NAME'] = 'My Flask App'
@app.route('/')
def hello_world():
return 'Hello, World!'
```

Initial Flask Support

---

src/scout_apm/core/core_agent_manager.py

If for any reason the manifest.json file isn't present or can't be opened, we
should catch that error.

Catch IOError when reading core-agent's manifest.json

---

src/scout_apm/celery/__init__.py

This is pretty bare bones currently, and hasn't been tested in very many cases, but it works well capturing my example Celery.  Note, that this currently relies on an unreleased version of the binary core-agent that will be released soon.
Tested on Python 3.6 with Celery 4.1.0.

Initial Celery Support

---

src/scout_apm/core/commands.py
src/scout_apm/core/request_manager.py
src/scout_apm/core/tracked_request.py
tests/scout_apm_tests/commands_test.py

This can come up if for some reason a Span isn't stopped, and its
timestamp is None. The code to create the StopSpan command explicitly
sets the kwarg to None, rather than leaving it off. So the defaulting
in `get` that existed didn't work (it was there as a key, just with a
value of None).
I applied this change to all Commands, since timestamps should always
exist, even if off.

Default a None timestamp in any Command to now

---

src/scout_apm/api/__init__.py
src/scout_apm/api/tracing.py
tests/scout_apm_tests/api/instrument_test.py

An easy API to instrument specific spans of code:
```
import scout_apm.api
@scout_apm.api.instrument("Custom/MyCalculation")
def my_calc(self, x, y):
pass
def my_other_calc(self, x, y):
with scout_apm.api.instrument("Custom/MyOtherCalculation") as instrument:
instrument.tag("user_id", "1")
pass
```
Questions:
* Should this be named `instrument`, or something more specific
* Should we limit the type prefix to be exactly "Custom"? If that string is high arity, it doesn't display well on the server. Elsewhere in the instrumentation it's "SQL" or "Template" or similar. Fixed strings.

Add simple ContextManager and Decorator for custom instrumentation

---

src/scout_apm/core/__init__.py
src/scout_apm/pyramid/__init__.py

To use, add the SCOUT_* settings to the Pyramid config, and then `config.include('scout_apm.pyramid')`
```python
import scout_apm.pyramid
if __name__ == '__main__':
with Configurator() as config:
config.add_settings(
SCOUT_KEY = '...',
SCOUT_MONITOR = True,
SCOUT_NAME = 'My Pyramid App'
)
config.include('scout_apm.pyramid')
```

Initial Pyramid Support

---

src/scout_apm/core/socket.py

Does not exist in 2.7 and FileNotFoundError inherits from OSError anyway.
https://docs.python.org/3/library/exceptions.html#exception-hierarchy

Remove FileNotFoundError

---

src/scout_apm/flask/__init__.py

A customer had a workflow where the ScoutApm() object was created before
the Flask app, and then the app was passed to `init_app`. Because we
didn't save it off at that point, it caused an exception when accessing
`self.app`.
```
scoutapm = ScoutApm()
def create_app():
app = Flask(__name__)
scoutapm.init_app(app)
```

Save App variable in Flask instruments `init_app(app)`

---

src/scout_apm/core/remote_ip.py
tests/scout_apm_tests/remote_ip_test.py

The header dictionary created by WSGI has keys with a prefix of `HTTP_`
But not for REMOTE_ADDR. Since that's not a user-provided value, and
instead generated by the server - it's not a header, but an extra bit of
data that lives with the headers

Fix RemoteIp class looking for the wrong keys in the header array

---

src/scout_apm/django/apps.py
src/scout_apm/django/middleware.py

For now, this is to support apps on Django 1.10+ that have updated from older
versions and stuck with MIDDLEWARE_CLASSES. These are not yet tested on older
Django versions.
I ran into this scenario when testing the open source project Spirit
(https://github.com/nitely/Spirit).

Add old style Django middleware instrumentation

---

CHANGELOG.md
setup.py
src/scout_apm/django/apps.py

Fixes a bug in Django <= 2 when both `MIDDLEWARE` and `MIDDLEWARE_CLASSES` are defined.

Reverse Django middleware insertion logic

---

src/scout_apm/core/thread_local.py

We've had customer reports of races in this class when run with python
async code, which uses finer-grained multithreading than actual threads.
Adding the lock here should fix this. It worked in socket.py.

Add a lock around ThreadLocalSingleton tasks

---

src/scout_apm/django/middleware.py

The signature was clearly wrong. I'm not sure what the effect was.

Fix OldStyleViewMiddleware.process_exception args.

---

src/scout_apm/core/samplers/cpu.py
tests/scout_apm_tests/tracked_request_test.py

Fix test_span_captures_backtrace, which passed in UTC-XX
and failed in UTC+XX.
Update CPU timing measurements for consistency.

Use UTC for timing measurements.

---

src/scout_apm/django/middleware.py

The attribute isn't there when the authentication middleware isn't
enabled. This situation was handled by the catchall try / except.
However a proper check is better to prevent a premature exit,,
in case new statements are added before the `except` clause.

Do not expect a request.user attribute.

---

src/scout_apm/api/__init__.py
src/scout_apm/bottle/__init__.py
src/scout_apm/core/config.py
src/scout_apm/core/ignore.py
src/scout_apm/core/tracked_request.py
src/scout_apm/django/middleware.py
src/scout_apm/flask/__init__.py
src/scout_apm/pyramid/__init__.py
tests/integration/test_api.py
tests/unit/core/test_ignore.py
tests/unit/core/test_tracked_request.py

Allows you to easily ignore /health and similar high-throughput, low
meaning endpoints. Any requests to paths that start with any of the
ignore list will not be sent, and hence not counted as Throughput, and
not averaged into average or 95th percentile response times, and no
traces will be captured.

New setting `ignore` to ignore path prefixes

---

DEVELOPMENT.md
requirements.txt
setup.py
tox.ini

A user reported that an automated GitHub security scan reported PyYAML
as being vulnerable [1].  The user also said that it doesn't appear that
we even use PyYAML. After some checking, it looks that he's right, we
don't use it.
My memory of how this dependency was ever added is that we pulled it in
as a dependency very early in development to implement configuration in
a similar way to how the Ruby agent does. But then, we implemented a
more Pythonic system for configuration.
The underlying security issue isn't relevant to or exploitable in our
agent. We never even import the PyYAML into our code, much less use the
potentially vulnerable `load` function. But of course, the most secure
code is code that doesn't exist. So this commit removes all mentions of
'pyyaml'.
[Closes #145]
[1]: …

Remove all references to PyYAML

---

src/scout_apm/core/config.py
src/scout_apm/core/core_agent_manager.py
src/scout_apm/core/util.py
tests/unit/core/test_config.py
tests/unit/core/test_util.py

Provides a new config option `core_agent_permissions` which allows users to choose the mode for creating the core agent directories.
Resolves #72

Core agent permissions

---

src/scout_apm/core/config.py
tests/integration/core/test_socket.py
tests/unit/core/test_config.py

In some edge cases, we're not able to automatically detect the host details of python, but we need that information to correctly download the binary component. This allows manual override. So far this has only come up in some Docker + Alpine Linux setups (but not all).

Add platform triple to config

---

src/scout_apm/core/commands.py

The log message was defaulting to use root logger config and not the logger configured for scoutapp

Fixes "Registering with app" log message not using configured logger

---

CHANGELOG.md
src/scout_apm/instruments/elasticsearch.py
tests/integration/instruments/test_elasticsearch.py

`elasticsearch-py` documented each method as taking the `index` parameter as a string (either a single index name or a comma separated list). The higher level library `elasticsearch-dsl-py` [forces using a list of strings](https://github.com/elastic/elasticsearch-dsl-py/blob/master/elasticsearch_dsl/search.py#L100) for the `index` parameter that it passes down to `elasticsearch-py`, which is supported but not documented as it is later serialized to a comma-separated list (in [`_make_path`](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/utils.py#L44)).
Our monkey patch on all the methods in `elasticsearch-py` only expected strings, this updates it to work with lists of strings as well. I added a test that failed before and passes after.
I've also made [a PR to …

Fix Elasticsearch integration for 'index' being passed as a list

---

CHANGELOG.md
src/scout_apm/django/middleware.py
tests/integration/django_app.py

This second middleware class for old versions of Django was missed when adding the functionality in #144.
Tested with local Django app on Django 1.9 and Python 2.7. I looked into adding tests but there's not any machinery atm for determining if requests would be tracked.

Fix 'ignore' functionality on Django < 1.10

---

CHANGELOG.md
src/scout_apm/instruments/elasticsearch.py
src/scout_apm/instruments/jinja2.py
src/scout_apm/instruments/pymongo.py
src/scout_apm/instruments/redis.py
src/scout_apm/instruments/urllib3.py

Fix warnings seen in tests such as:
```
tests/integration/instruments/test_jinja2.py::test_installable
tests/integration/instruments/test_jinja2.py::test_install_is_idempotent
/private/tmp/tox/py37-django22/lib/python3.7/site-packages/scout_apm/instruments/jinja2.py:22: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
logger.warn("Jinja2 Instruments are already installed.")
tests/integration/instruments/test_jinja2.py::test_install_failure
/private/tmp/tox/py37-django22/lib/python3.7/site-packages/scout_apm/instruments/jinja2.py:50: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
logger.warn("Unable to instrument for Jinja2 Template.render: %r", e)
```

Fix warnings for deprecated method logger.warn

---

README.md

Not 100% black formatted since it's easier to read the separated keys one per line, especially in tutorial code.

Make code examples in README more flake8 and black friendly

---

src/scout_apm/django/apps.py

Whilst improving the tests, I discovered that the way the Django test setup works, the app.ready() gets called in every test. This was causing the middleware to have multiple copies inserted.
Change this so that if a middleware is already in the stack, it doesn't get re-added. This will also let users organize the middleware if they so wish.

Make Django middleware addition idempotent

---

pytest.ini
setup.cfg
tox.ini

Allow passing arguments through rather than whole commands with {posargs}, always have coverage using pytest `addopts`, and use modern `pytest` name rather than deprecated `py.test`.

Improve tox + pytest setup

---

CHANGELOG.md
src/scout_apm/django/instruments/sql.py
src/scout_apm/django/instruments/template.py
src/scout_apm/django/middleware.py
tests/conftest.py
tests/integration/test_django.py

Split from #167.
The `tracked_requests` fixture intercepts all the requests that would go into `RequestBuffer` so assertions can be made on them.
Adding these assertions has revealed a number of bugs, only some of which I'm fixing here:
* Repeated spans - the middleware seems is re-installed repeatedly in tests, but it doesn't uninstall itself, so the instruments were installed on top of each other a lot. I've fixed this for now by making the installs idempotent, like the middleware, but long term will be making the django app only get installed once during tests.
* Username tracking wasn't implemented in the old Django middleware
* The test to disable monitoring doesn't really disable it because Scout is fully installed by the time the test runs. Some refactoring is needed here.

Test tracked requests and fix username tracking on Django < 1.10

---

tests/conftest.py
tests/integration/test_flask_sqlalchemy.py

Fix these warnings:
```
/private/tmp/tox/py37-django22/lib/python3.7/site-packages/webtest/app.py:89
/private/tmp/tox/py37-django22/lib/python3.7/site-packages/webtest/app.py:89
/private/tmp/tox/py37-django22/lib/python3.7/site-packages/webtest/app.py:89
/private/tmp/tox/py37-django22/lib/python3.7/site-packages/webtest/app.py:89
/private/tmp/tox/py37-django22/lib/python3.7/site-packages/webtest/app.py:89: PytestWarning: cannot collect test class 'TestApp' because it has a __init__ constructor
class TestApp(object):
tests/integration/test_flask_sqlalchemy.py::test_hello
/private/tmp/tox/py37-django22/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py:835: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future. …
```

Fix some warnings in tests

---

tests/unit/core/test_tracked_request.py

This test would fail when running just its containing file on Python 3 with:
```
>       assert span.tags["allocations"] > 0
E       assert 0 > 0
```
Turns out `objtrace.enable()` needs calling to ensure it does track.
There's no easy way of making a test fixture that resets the enabled/disabled state at the end of it, but there probably isn't a need anyway as `install()` does `objtrace.enable()` anyway.

Fix randomly failing test test_tags_allocations_for_spans

---

src/scout_apm/core/tracked_request.py
tests/unit/core/test_tracked_request.py

Output some partial information on each in order to make test authoring easier.

Implement __repr__ on TrackedRequest and Span

---

CHANGELOG.md
src/scout_apm/flask/__init__.py
tests/integration/test_flask.py

* Add failing test `test_hello_options` that shows how Monkey-patched `dispatch_request` missed Flask's `provide_automatic_options` behaviour
* Remove `process_request` and `process_response` hooks which have been empty since #99
* Stop entirely monkey patching `dispatch_request` ([Flask source](https://github.com/pallets/flask/blob/d4b688bd035b9704b3168b28fed39c8fcfe3b997/src/flask/app.py#L1872c)) and instead wrap it with a `CallableProxy` around `wrapped_dispatch_request`. This fixes the current divergence around `provide_automatic_options` and guards against potential future divergence.
* Remove the `try/except Exception` around putting in place `CallableProxy`, since we're no longer wrapping each view function but only the one method. This will fail at startup if it's not possible, …

Fix Flask to track missed automatic OPTIONS requests

---

src/scout_apm/instruments/elasticsearch.py
src/scout_apm/instruments/jinja2.py
src/scout_apm/instruments/pymongo.py
src/scout_apm/instruments/redis.py
src/scout_apm/instruments/urllib3.py
tests/integration/instruments/test_elasticsearch.py
tests/integration/instruments/test_jinja2.py
tests/integration/instruments/test_pymongo.py
tests/integration/instruments/test_redis.py
tests/integration/instruments/test_urllib3.py

I saw some test failures like this while writing #188:
```
/tmp/tox/py36-django111/lib/python3.6/site-packages/scout_apm/instruments/elasticsearch.py:179: in perform_request
return original(*args, **kwargs)
/tmp/tox/py36-django111/lib/python3.6/site-packages/scout_apm/core/monkey.py:199: in __call__
self.__subject__, self._eop_instance_, *args, **kwargs
/tmp/tox/py36-django111/lib/python3.6/site-packages/scout_apm/instruments/elasticsearch.py:179: in perform_request
return original(*args, **kwargs)
/tmp/tox/py36-django111/lib/python3.6/site-packages/scout_apm/core/monkey.py:199: in __call__
self.__subject__, self._eop_instance_, *args, **kwargs
/tmp/tox/py36-django111/lib/python3.6/site-packages/scout_apm/instruments/elasticsearch.py:179: in perform_request
return original(*args, …
```

Move all instrument installed tracking to class level

---

.travis.yml
tox.ini

This ensures that the package is built in a valid format for PyPI, including the README syntax. Run it on both tox and travis wheel building steps - tox to fail early, and travis to be exhaustive on all the built wheels.

Run 'twine check' in tests

---

CHANGELOG.md
README.md
src/scout_apm/falcon.py
tests/integration/test_falcon.py
tox.ini

Fixes #179. Add a middleware that implements basic tracking of Falcon resources, with operations named after the current resource name plus the method called on it. The method name is retrieved through stack inspection, which can fail and in that case we use the raw HTTP method name instead.

Add Falcon integration

---

CHANGELOG.md
src/scout_apm/bottle.py
tests/integration/test_bottle.py
tests/integration/test_django.py
tests/integration/test_falcon.py
tests/integration/test_flask.py
tests/integration/util.py

* Remove always overridden `path = "Unknown"`
* Replace accessing [request.remote_addr](https://bottlepy.org/docs/dev/api.html#bottle.BaseRequest.remote_addr) with our custom "get the user's IP algorithm" that does a little more and will be consistent across frameworks
* Reduce size of `try/except` clauses to make it obvious which things are expected to be able to fail
* Improve test coverage to 100%
* Deduplicate tests on `user_ip` tag with `@parametrize_user_ip_headers`

Tidy Bottle integration

---

README.md

* Reduce Python version description to a single sentence to use less space
* Alphabetically sort the list of frameworks, as they are sorted like that below
* Deduplicate "for full installation" sentences under the "Documentation" header

Tidy README a bit

---

CHANGELOG.md
src/scout_apm/pyramid.py
tests/integration/test_pyramid.py

* Rearrange `try/except` so `stop_span()` will only be called if it was started
* Use and test the full `user_ip` algorithm rather than just `request.remote_addr`, and reduce scope of its `try/except`
* Improve some tests

Improve Pyramid integration

---

src/scout_apm/core/config.py
src/scout_apm/core/core_agent_manager.py
src/scout_apm/instruments/urllib3.py
tests/integration/core/test_core_agent_manager.py

Use `logger.exception` instead of `logger.error` so the full traceback is displayed, as suggested by Aymeric.

Improve exception logging

---

tests/integration/test_pyramid.py

After looking at whether this is needed in all tests for non-tracking, I realized this is already done for each test by the `isolate_global_state` fixture in `tests/conftest.py`. Therefore removing the redundant assertions added in #195.

Remove unnecessary assertions in Pyramid tests

---

src/scout_apm/core/config.py
src/scout_apm/django/apps.py
tests/integration/django_app.py
tests/integration/test_django.py

The existing tests did not reset Django to a clean state each time, since the scout_apm app was being repeatedly re-installed and uninstalled, but it didn't do anything to reset settings on uninstall. This is what lead to me implementing idempotent middleware addition in #168.
This PR refactors the way configuration is done. The test Django app is initialized only once, with Scout already installed. Scout then synchronizes the Django settings into ScoutConfig, and listens to Django's `setting_changed` signal to keep them in sync. Rather than rely on reset_all at the end of each test, I added an assertion that no settings have been left in place by any test - if they all use `override_settings` to change the settings, this will be the case.
This has let me write tests that cover all the …

Refactor Django configuration

---

tox.ini

These are not used, remove to avoid confusion.

Remove coveralls and codecov tox configuration

---

CHANGELOG.md
src/scout_apm/core/queue_time.py
src/scout_apm/django/middleware.py
src/scout_apm/falcon.py
tests/conftest.py
tests/integration/test_django.py
tests/integration/test_falcon.py
tests/unit/core/test_queue_time.py

Implement #120 for this integration. This required making `track_request_queue_time` a generic function usable by all the integrations.

Implement request queue timing in Falcon

---

CHANGELOG.md
src/scout_apm/bottle.py
src/scout_apm/flask/__init__.py
src/scout_apm/pyramid.py
tests/integration/test_bottle.py
tests/integration/test_django.py
tests/integration/test_falcon.py
tests/integration/test_flask.py
tests/integration/test_pyramid.py
tests/integration/util.py

Add #120 for these three integrations, using the shared function extracted from the Django integration for Falcon in #199.

Implement request queue time tracking in Bottle, Flask, and Pyramid

---

CHANGELOG.md
setup.cfg
src/scout_apm/core/cli/core_agent_manager.py
tests/unit/core/cli/test_core_agent_manager.py

Fixes #120. Steps:
* Added a call to `AgentContext.build()` to restore functionality. This is the
only thing that broke. I used `git bisect` to discover that it was broken in
6ab579e22ab903bb6b72108bc485550bb151f353, which is when `AgentContext` was
refactored.
* Refactored to remove the unnecessary extra functions for the subparsers
* Removed unnecessary subparser name validity check, as this is done by
argparse already
* Restored test coverage checking for the file
* Added some basic tests to get to 100% coverage

Fix core-agent-manager

---

CHANGELOG.md
src/scout_apm/django/middleware.py
tests/integration/test_django.py

* In both old and new style middleware, mark requests as real only when we hit `process_view`. This means we don't track responses generated by other middleware *before* a view, which may not be desirable, but at least we're consistent between the two implementations for now.
* Be more cautious in the old style middleware, to keep track of the TrackedRequest we have assigned to the current Django request. Unbalanced spans should be less likely.
* Remove `finish_tracked_request_if_old_style_middlware` test fixture, which was really papering over the bugs to do with unbalanced spans.
* Test a lot more cases with old style middleware with other middleware in the stack generating early responses or exceptions, to cover many more scenarios.

Improve Django middleware tracking

---

tests/integration/django_app.py
tests/integration/test_django.py

* Don't use DEBUG mode in tests - this means we're testing against a more "production ready" Django app
* Group asserts properly according to the AAA pattern

Tidy Django tests

---

src/scout_apm/core/config.py
tests/unit/core/test_config.py

`assert` shouldn't be used in production code since Python's (rarely used) optimize flag (`python -O`) strips them out. Also get the code coverage of this module to 100%.

Remove assertion in config

---

CHANGELOG.md
src/scout_apm/core/core_agent_manager.py

Fixes #216.
This is the default [on Python 3.4+](https://docs.python.org/3/library/os.html#fd-inheritance).
Tested with https://github.com/adamchainz/scout-test-apps/commit/61f0197e5731c3a6709a1520d08a2102d53a0217 before and after, checking `lsof -nP -i :8000` to see if the core agent process was holding onto the port.

Close file descriptors when launching core agent

---

tox.ini

This was done in 986d17cddeecf73a457ac2766b3e5686ac005cbe but I'm not sure why. It's better for my workflow to keep it in the standard directory so that virtualenvs don't need rebuildingn so frequently when `/tmp` gets cleared.

Move to standard toxworkdir

---

CHANGELOG.md
src/scout_apm/flask/__init__.py
tests/integration/test_flask.py

This was previously being tagged on the span, rather than the tracked request itself, which meant it was not seen by the core agent / UI.

Fix path tagging on Flask

---

CHANGELOG.md
src/scout_apm/celery.py
tests/integration/test_celery.py

Fixes #34. Tagging with the current *queue* is only *sometimes* possible - often the *exchange* and *routing_key* are provided instead. The task may have come from a particular queue, but its delivery information normally onyl tracks where it was sent at the top of the AMQP funnel by exchange + routing_key, since that's what's needed for retry. Also track the `is_eager` flag which may be useful for determining which way the task was run.
More information on these parameters can be gleaned from [the source](https://github.com/celery/celery/blob/8cf8fae70630954cff3448485588bbe2a77ff3ab/celery/app/task.py#L600).
Updating the tests to use the fixture added in Celery 4.0, but since we support 3.1 this is in a conditional test. Our test suite currently installs the latest version of Celery …

Add extra Celery tags

---

CHANGELOG.md
src/scout_apm/celery.py
tests/integration/test_celery.py

Fixes #35. Track the queue time by using an extra haeder to track when the task is added to the queue and comparing when it gets executed. This should work in most setups but if the celery app isn't all set up on the producer side, we are well defended against it.
Like #205, I manually tested on Celery 3.1.x locally by editing `tox.ini` and reinstalling with `tox -r`.

Track queue time on Celery

---

src/scout_apm/core/config.py
src/scout_apm/core/platform_detection.py
tests/unit/core/test_platform_detection.py

Unnecessary class methods moved to module functions, as per Aymeric's list. Also add caching on `get_libc()` since it uses a subprocess and might be called in cases where the core agent is started more than once, and add `close_fds=True` to the call to `ldd` like #219 did for launching the core agent, just in case.

Flatten PlatformDetection class methods into module

---

CHANGELOG.md
src/scout_apm/django/middleware.py
tests/integration/django_app.py
tests/integration/test_django.py

Improve Django admin views' traced names

---

tests/integration/django_app.py
tests/integration/test_django.py

Following #226, test the trace names for Django class-based views. Although they are good as-is and aren't changing, I wanted to add tests to check that future changes such as #102 don't make them worse.

Test Django class based view

---

src/scout_apm/core/queue_time.py
src/scout_apm/core/util.py
tests/unit/core/test_queue_time.py
tests/unit/core/test_util.py

Put it next to the queue time tools and out of the ambiguously named 'util' module.

Move convert_ambiguous_timestamp_to_ns

---

CHANGELOG.md
src/scout_apm/core/socket.py

* Add exception in the "thread exception" message
* Pass `exc_info=exc` so if the messages are picked up by a formatter that works with exceptions, it uses them.

Improve logging in CoreAgentSocket

---

src/scout_apm/core/commands.py
tests/unit/core/test_commands.py

These classes are unused except in tests, so drop them according to the YAGNI principle.

Drop CoreAgentVersion and CoreAgentVersionResponse

---

CHANGELOG.md
src/scout_apm/core/config.py
tests/unit/core/test_config.py

The core agent has used the default socket name `scout-agent.sock` when started solo since version 1.0.0. Python has been starting it with a different socket name, which could lead to multiple agents running on different sockets if multiple languages are used.

Update default socket path

---

src/scout_apm/core/samplers/cpu.py
tests/unit/core/samplers/__init__.py
tests/unit/core/samplers/test_cpu.py
tests/unit/core/samplers/test_memory.py

This revealed a few bugs in `Cpu`:
* The first defensive log message was broken in terms of expected format parameters. I dropped the last one.
* The last branch defending against `res < 0` was unreacahable since the two divisors had already been verified as not being negative, so the division could not end up negative.

Add test coverage for samplers

---

src/scout_apm/core/socket.py

I realized that this method has a read-after-write concurrency bug here - if the thread stops successfully but another restarts the thread between the call to `wait()` and `is_set()`, it could incorrectly report failure to stop. `wait()` already returns the value of the event so there's no need to reread here.

Fix race condition in CoreAgentSocket.stop()

---

CHANGELOG.md
src/scout_apm/core/samplers/cpu.py
tests/unit/core/samplers/test_cpu.py

Spotted whilst adding test coverage in #242.
The [`psutil.cpu_count` docs](https://psutil.readthedocs.io/en/latest/#psutil.cpu_count) say it can return `None` in the case that the CPU count cannot be determined. This would lead to a `TypeError` in the multiplication, so fix that by assuming 'undetermined' means one CPU - incorrect statistics, but better than nothing.

Guard against undetermined CPU count

---

src/scout_apm/core/commands.py
tests/unit/core/test_commands.py

They're only internal so it's fine for them to require arguments rather than use the slower `kwargs.get` with some defaults which might still break the core agent.
Also use `__slots__` for a minor speed boost.

Minimize command classes

---

src/scout_apm/django/instruments/template.py

This never worked and it's not clear to me what the value of tagging the context would be.

Remove commented Django Template context tracking

---

tests/integration/django_app.py
tests/integration/test_django.py

Test that we instrument template renders done by `TemplateResponse`, which renders later in the cycle. Check that early rendering isn't forced by using a decorator that modifies the Template response's context as it leaves the view.

Add Django TemplateResponse test

---

src/scout_apm/core/config.py
src/scout_apm/core/platform_detection.py
tests/conftest.py
tests/integration/core/test_core_agent_manager.py
tests/unit/core/samplers/test_cpu.py
tests/unit/core/samplers/test_memory.py
tests/unit/core/test_config.py
tests/unit/core/test_platform_detection.py

Fixes #241. Also override `caplog` to always be at DEBUG level to DRY tests a bit and ensure we always assert on all log messages.

Validate overridden values for core_agent_triple

---

src/scout_apm/core/commands.py
src/scout_apm/core/thread_local.py
src/scout_apm/core/tracked_request.py
tests/unit/core/test_commands.py
tests/unit/core/test_tracked_request.py

Replicate the changes from #255 into these key classes. Also remove unused constructor arguments and rename `req_id` to `request_id`.

Minimize TrackedRequest and Span classes

---

tests/unit/core/test_tracked_request.py

Remove the redundant `tr` fixture as the `tracked_request` one from the root conftest can be used, and some other minor tidy cleanup.

Refactor Tracked Request tests

---

src/scout_apm/django/middleware.py

Small tidy up in new middleware to avoid refteching the `TrackedRequest` instance.

Tidy Django middleware span balancing

---

tests/integration/django_app.py
tests/integration/test_bottle.py
tests/integration/test_django.py
tests/integration/test_flask.py

I've been uncommenting these enough during different test workflows that I think it's better to have them permanently on and disable them in the few tests that need to.

Enable web frameworks' exception propagation flags in tests

---

setup.cfg
setup.py
src/scout_apm/core/monkey.py
src/scout_apm/core/web_requests.py
tests/conftest.py
tests/integration/app.py
tests/integration/core/__init__.py

Most files already have them, but missing them in some files could lead to bugs, especially with `unicode_literals`.

Configure isort to always require all __future__ imports

---

CHANGELOG.md
src/scout_apm/django/middleware.py
tests/integration/test_django.py

Since Django supports changing it through `request.urlconf`, we should capture it, as it will indicate which version of a URL/view is in use.

Track urlconf on Django

---

CHANGELOG.md
src/scout_apm/bottle.py
src/scout_apm/core/web_requests.py
src/scout_apm/django/middleware.py
src/scout_apm/falcon.py
src/scout_apm/flask/__init__.py
src/scout_apm/nameko.py
src/scout_apm/pyramid.py
tests/integration/test_bottle.py
tests/integration/test_django.py
tests/integration/test_falcon.py
tests/integration/test_flask.py
tests/integration/test_nameko.py
tests/integration/test_pyramid.py
tests/unit/core/test_web_requests.py

Track Amazon request queue time

---

CHANGELOG.md
src/scout_apm/core/core_agent_manager.py

Fix this warning from emittig this warning:
> DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead

Fix logging warning

---

setup.py

According to [the documentation](https://packaging.python.org/guides/distributing-packages-using-setuptools/#py-modules), this is only for shipping Python modules that aren't in a package. We ship everything in one package so we therefore don't need it.

Remove py_modules from setup.py

---

setup.py

* Always read `README.md`. It's always there in the source distribution so this should never fail - if it does we've made a packaging mistake. The check was added in 2d3f3464aabb9455e4c3218e2d8580e7efc00983 , which predates the README being included in `MANIFEST.in` in 46921dedf35bf6b2e5e77d47f2e134c7ff849af0 .
* Merge all `compile_extensions` logic into a single statement to avoid evaluating every step when not needed.
* Avoid double-negative in determining ext_modules - define before including
* Convert dict + `**kwargs` into single function call

Simplify setup.py

---

setup.py

This will prevent new releases from breaking us unexpectedly.

Pin to major versions of requirements

---

src/scout_apm/core/web_requests.py
src/scout_apm/flask/__init__.py
src/scout_apm/nameko.py

Flask and Nameko both use Werkzeug requests, and had basically copy-pasted blocks of code to call the underlying pieces. DRY that out with a single function.

Deduplicate Werkzeug request data tracking

---

setup.cfg

I simplified it in #175 to only the parts we use. Ideally they should have coverage in our code base, or we should finish moving to `wrapt`.

Don't omit monkey.py from coverage

---

src/scout_apm/bottle.py
src/scout_apm/pyramid.py
tests/integration/test_bottle.py
tests/integration/test_pyramid.py

Both the Bottle and Pyramid integrations have this overly cautious behaviour around reading headers from the upstream framework. They both assume that basic framework operations such as fetching a header can fail, and guard around it.
Some of this came from my refactoring for Bottle in #192 and Pyramid in #195, where I narrowed large `try/except` blocks down, but didn't rethink this paranoia.
I think this is too cautious and can be removed. It required a lot of extra lines for the two frameworks when adding Amazon request queue timing in #279, to really no extra effect. If fetching headers (with safe defaults) is broken, users' applications are pretty much guaranteed to be broken too.

Remove overly cautious header fetching behaviour

---

src/scout_apm/core/samplers/cpu.py
src/scout_apm/core/samplers/memory.py
src/scout_apm/core/samplers/thread.py
src/scout_apm/core/tracked_request.py
tests/unit/core/samplers/test_cpu.py
tests/unit/core/samplers/test_memory.py

Following looking at them inn #307:
* Make `metric_type`, `metric_name`, and `human_name` simple class properties since they never change
* Remove static methods from `Memory`, simplifying down to a function `get_rss_in_mb()` and the delta method on `TrackedRequest`

Simplify samplers

---

src/scout_apm/core/__init__.py
tests/unit/test_core.py

I saw that flake8's `is_windows()` check prefers `os.name`, and it seems simpler.

Change Windows check

---

src/scout_apm/api/__init__.py
src/scout_apm/bottle.py
src/scout_apm/core/tracked_request.py
src/scout_apm/django/middleware.py
src/scout_apm/falcon.py
src/scout_apm/flask/__init__.py
src/scout_apm/nameko.py
src/scout_apm/pyramid.py
tests/unit/core/test_tracked_request.py

Use a flag rather than magic string matching. This also:
* Removes the accidentally committed check for the magic string `QueueTime/Request` (from #167, before going in a different direction than using a span) 
* Makes custom instrumented transactions ignore their top level spans, no matter the name, which was skipped before.

Span flag should capture backtrace

---

CHANGELOG.md
setup.cfg
src/scout_apm/api/__init__.py
src/scout_apm/core/instrument_manager.py
src/scout_apm/core/web_requests.py
tests/integration/core/test_core_agent_manager.py
tests/integration/test_api.py
tox.ini

Add this Flake8 plugin which has some good extra rules and is the recommended way of checking about Black's line length.
Fix these issues it flagged:
```
src/scout_apm/core/instrument_manager.py:22:22: B009 Do not call getattr with a constant attribute value, it is not any safer than normal property access.
src/scout_apm/core/web_requests.py:11:182: B950 line too long (181 > 80 characters)
src/scout_apm/api/__init__.py:45:55: B006 Do not use mutable data structures for argument defaults.  They are created during function definition time. All calls to the function reuse this one instance of that data structure, persisting changes between them.
src/scout_apm/api/__init__.py:73:35: B006 Do not use mutable data structures for argument defaults.  They are created during function definition …
```

Lint with flake8-bugbear

---

tests/integration/instruments/test_elasticsearch.py
tests/integration/instruments/test_pymongo.py
tests/integration/instruments/test_redis.py
tests/integration/instruments/test_urllib3.py
tests/integration/test_dramatiq.py

For two reasons:
1. These cause the test modules to not be collected so the tests don't even count as skipped in Pytest's output
2. Many of the tests within the modules don't actually rely on running servers so it's best to run them when we can!

Remove module-based test skips

---

src/scout_apm/bottle.py
src/scout_apm/core/__init__.py
src/scout_apm/core/config.py
src/scout_apm/core/context.py
src/scout_apm/core/core_agent_manager.py
src/scout_apm/core/instrument_manager.py
src/scout_apm/core/metadata.py
src/scout_apm/core/socket.py
src/scout_apm/core/web_requests.py
src/scout_apm/django/apps.py
src/scout_apm/django/middleware.py
src/scout_apm/flask/__init__.py
src/scout_apm/pyramid.py
tests/integration/core/test_core_agent_manager.py
tests/integration/test_api.py
tests/unit/core/test_context.py
tests/unit/core/test_instrument_manager.py
tests/unit/core/test_web_requests.py

Whilst investigating making the agent context configurable with running under async, I realized the `ScoutConfig` class does little as an instance - all the state is stored in globals and classes. Yet we recreate instances all over the place.
This PR turns into a true global object, a single instance of the class, so it's easier to import and share.

Make config object global

---

tests/integration/test_bottle.py
tests/integration/test_django.py
tests/integration/test_falcon.py
tests/integration/test_flask.py
tests/integration/test_nameko.py
tests/integration/test_pyramid.py
tests/unit/core/test_web_requests.py

Have been seeing rare failures on Travis like:
```
=================================== FAILURES ===================================
_ test_track_amazon_request_queue_time_valid[Root=1-{start_time}-12456789abcdef012345678;CalledFrom=app] _
header_value = 'Root=1-{start_time}-12456789abcdef012345678;CalledFrom=app'
tracked_request = <TrackedRequest(request_id='req-ca2b1c89-b2b7-4f9a-b5a8-ffbde626c511', tags={'scout.queue_time_ns': 1999785984})>
@pytest.mark.parametrize(
"header_value",
[
"Root=1-{start_time}-12456789abcdef012345678",
"Root=1-{start_time}-12456789abcdef012345678;CalledFrom=app",
"Self=1-{start_time}-12456789abcdef012345678",
"Self=1-{start_time}-12456789abcdef012345678;Root=1-123-abcdef012345678912345678",  # noqa: E501 …
```

Attempt to fix timing bug on Travis

---

tests/integration/instruments/test_elasticsearch.py
tests/integration/instruments/test_pymongo.py
tests/integration/instruments/test_redis.py
tests/integration/instruments/test_urllib3.py

Since #320 some of these tests have started failing when the respective libraries are not available. To fix them I removed some of the precondition assertions which don't hold if the other tests get skipped, and made some more of the Redis tests automatically get skipped.

Fix some instrument tests

---

src/scout_apm/api/__init__.py
src/scout_apm/bottle.py
src/scout_apm/celery.py
src/scout_apm/core/tracked_request.py
src/scout_apm/django/middleware.py
src/scout_apm/dramatiq.py
src/scout_apm/falcon.py
src/scout_apm/flask/__init__.py
src/scout_apm/nameko.py
src/scout_apm/pyramid.py
tests/conftest.py
tests/unit/core/test_tracked_request.py

Remove the unnecessary level of indirection from the methods. Generally in Python if we have a simple attribute, we don't need to add getters or setters.

Move is_real_request to attribute

---

setup.cfg
src/scout_apm/django/instruments/sql.py
tests/integration/app.py
tox.ini

Prevent print() statements from getting into committed source code. This found some I accidentally left in #324, plus two in the 'integration all-in-one app' that I've rewritten with logging.

Lint with flake8-print

---

src/scout_apm/core/stacktracer.py
src/scout_apm/django/instruments/template.py
tests/unit/core/test_stacktracer.py

This code hasn't been active since it was added in the first commit: 4de21f8ea228a082d4f039c0c991ee41dfb6f9d8. Remove it for now, though it could provide a useful starting point for reimplementation in issue #313.

Remove dead Django custom template tag instrumentation

---

src/scout_apm/instruments/redis.py
tests/integration/instruments/test_redis.py

Avoid importing in a function but do it up front once. Reduce `try / except` to assume that `wrapt.decorator` works.

Improve Redis import pattern

---

src/scout_apm/core/__init__.py
src/scout_apm/core/metadata.py
tests/unit/core/test_metadata.py

Fixes #346.
The big `try/except` didn't seem to be guarding against anything useful - if the unguarded statements inside don't work, it's unlikely any of the other parts of Scout will (`sys.version_info`, `dt.datetime.utcnow()`, and `scout_config.value` are pretty core).
Also remove the unnecessary class.

Simplify application metadata

---

CHANGELOG.md
src/scout_apm/instruments/elasticsearch.py
tests/integration/instruments/test_elasticsearch.py

Part of #342.
Also tidy up the import pattern, smiilar to Redis changes in #341, and fix index name tracking when not passed as a keyword argument.
The speed difference is smaller than I thought.
Before:
```
In [2]: %timeit Instrument().install(); Instrument().uninstall()
95.5 µs ± 2.07 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
After:
```
In [2]: %timeit Instrument().install(); Instrument().uninstall()
89.5 µs ± 674 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
However the other benefits still stand - code being linted, etc.

Remove exec calls from Elasticsearch instrument

---

CHANGELOG.md
src/scout_apm/core/socket.py

Both @naohiro-t and I have seen the socket time out during startup only to reconnect shortly after:
```
2019-08-30T09:25:10+0100 DEBUG Parsing Core Agent manifest path: /tmp/scout_apm_core/scout_apm_core-v1.1.8-x86_64-apple-darwin/manifest.json
2019-08-30T09:25:10+0100 DEBUG Core Agent manifest json: {u'core_agent_version': u'1.1.8', u'core_agent_binary': u'core-agent', u'version': u'1.1.8', u'core_agent_binary_sha256': u'2896f584cb373c596164805510531a34b29e4eb34a13685edd4c6df364161414'}
[2019-08-30T08:25:10][core_agent][INFO] Initializing logger with log level: Info
2019-08-30T09:25:11+0100 DEBUG CoreAgentSocket thread exception: timeout('timed out',)
Traceback (most recent call last):
File "/Users/chainz/Documents/Projects/scout_apm_python/src/scout_apm/core/socket.py", line 105, in run …
```

Increase socket timeout

---

src/scout_apm/core/tracked_request.py
tests/unit/core/test_commands.py
tests/unit/core/test_tracked_request.py

Restrict the arguments to require `operation` and prevent overriding of others such as the span ID.

Tidy TrackedRequest.start_span

---

tests/integration/test_django.py
tests/unit/core/test_stacktracer.py

It seems these aren't needed, probably Flake8 updated to remove some false positives.

Remove unnecessary noqas

---

CHANGELOG.md
src/scout_apm/bottle.py

Checking the result of `scout_apm.core.install()` brings it in line with other integrations, and means the tracking will be disabled if we fail to download the agent, are running on Windows, etc.

Correctly disable Bottle when agent fails to launch

---

src/scout_apm/instruments/jinja2.py
src/scout_apm/instruments/urllib3.py
tests/integration/instruments/test_elasticsearch.py
tests/integration/instruments/test_jinja2.py
tests/integration/instruments/test_urllib3.py

Modify the last two instruments to do import-time importing, rather than re-importing in several different places. This is the same as done for Redis in #341.

Tidy jinja2 and urllib3 import patterns

---

src/scout_apm/huey.py
tests/integration/test_huey.py

Ensure `scout_apm.core.install()` is called in the Huey integration, and don't monitor if install fails.

Ensure install() is called for Huey

---

setup.py
src/scout_apm/core/context.py

For example, Channels 1 applications require old asgiref versions < 3.1, which added `asgiref.local.Local`. Therefore remove version requirement on asgiref and add a poorer version of `asgiref.local` that doesn't know about `sync_to_async` / `async_to_sync` for those cases.

Support older asgiref versions

---

pytest.ini

Prevent this error in the Python 3.5 environment:
```
ImportError while importing test module '/Users/chainz/Documents/Projects/scout_apm_python/src/scout_apm/async_/__init__.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
ImportError: No module named 'scout_apm.async_'
```
It seems the latest version of Pytest checks for tests in the repo src directory but then tries to import those modules from the installed directory. It can't import `scout_apm.async_` since it doesn't exist on Python < 3.6 due to logic in the `setup.py`.
This fixes it by telling it not to look in `src/` ever.

Stop Pytest collecting tests from src/

---

src/scout_apm/core/metadata.py

Now it errors on `list(sorted(x))` because `sorted()` already returns a list.

Fix for upgraded flake8-comprehensions

---

CHANGELOG.md
src/scout_apm/core/_objtrace.c
src/scout_apm/core/objtrace.py
tests/integration/test_api.py
tests/tools.py
tests/unit/core/test_commands.py
tests/unit/core/test_objtrace.py

Broken in #303 and not detected due to test suite skipping the tests, which need skipping on Python 2.7 because the extension isn't compatible with it.

Fix objtrace C extension

---

src/scout_apm/falcon.py
tests/integration/test_falcon.py

Ref #383.
Also, since Falcon allows directly setting the status line, test the case where a bad one is set, and report that as an error too.

Tag Falcon 5XX responses as errors

---

tests/integration/test_django.py

A small tidy up - since this is internal code it should use the internal form of the API. The external one should be restricted for users.

Move Django tests to use internal config name

---

src/scout_apm/celery.py
src/scout_apm/compat.py
src/scout_apm/core/metadata.py
src/scout_apm/core/samplers/cpu.py
src/scout_apm/core/samplers/thread.py
src/scout_apm/core/tracked_request.py
src/scout_apm/rq.py
tests/compat.py
tests/integration/test_bottle.py
tests/integration/test_django.py
tests/integration/test_falcon.py
tests/integration/test_flask.py
tests/integration/test_nameko.py
tests/integration/test_pyramid.py
tests/integration/test_starlette_py36plus.py
tests/unit/core/samplers/test_cpu.py
tests/unit/core/test_tracked_request.py
tests/unit/core/test_web_requests.py
tests/unit/test_compat.py

Fixes #368. Avoids ambiguous datetimes throughout the system.

Refactor use of utcnow to now(tz=utc)

---

src/scout_apm/celery.py
src/scout_apm/compat.py
src/scout_apm/core/metadata.py
src/scout_apm/core/samplers/cpu.py
src/scout_apm/core/samplers/thread.py
src/scout_apm/core/tracked_request.py
src/scout_apm/rq.py
tests/integration/test_bottle.py
tests/integration/test_django.py
tests/integration/test_falcon.py
tests/integration/test_flask.py
tests/integration/test_nameko.py
tests/integration/test_pyramid.py
tests/integration/test_starlette_py36plus.py
tests/unit/core/samplers/test_cpu.py
tests/unit/core/test_tracked_request.py
tests/unit/core/test_web_requests.py
tests/unit/test_compat.py

PR #397 has lead to timezone offsets being sent to the Core Agent, which it doesn't parse, logging this error and failing to return a full response to the client:
```
[2019-11-25T18:09:49][socket::server][INFO] Reading a command from stream: NoParse(Error("trailing input", line: 1, column: 70), "{\"ApplicationEvent\": {\"timestamp\": \"2019-11-25T18:09:49.328081+00:00Z\", \"event_type\": \"CPU/Utilization\", \"event_value\": 0.027687317280944007, \"source\": \"Pid: 69721\"}}")
```
I think the safest thing to do here is a pure revert. It would be better theoretically to track datetimes with timezone information but it seems too disruptive to the way the core agent works.

Revert utcnow change

---

tox.ini

Only pass the environment variables we know the test suite uses. This prevents unintended overrides. `SCOUT_*` env vars are already cleared in `conftest.py` thanks to 475620d3 but this is a more solid approach.

Remove passenv = * from tox config

---

CHANGELOG.md
src/scout_apm/core/backtrace.py
tests/tools.py
tests/unit/core/test_backtrace.py

Make it faster by using a split implementation based on the Python version, and a list comprehension
Combine the tests since they really all tested one output.
Avoid capturing the frame for `capture()` itself, as per comment in tests - it's not very useful information to the user.

Rewrite backtrace and tests

---

.pre-commit-config.yaml
DEVELOPMENT.md
MANIFEST.in
setup.cfg
tox.ini

Use [pre-commit](https://pre-commit.com/) to lint on every commit and save time from creating PR's only to watch them fail code style checks on CI.
Rewrite the docs for a simpler tox-centric setup process and how to install pre-commit.

Lint with pre-commit

---

CHANGELOG.md
src/scout_apm/core/config.py

(from CA's changelog)
[1.2.6] 2019-12-03
Fixed:
* Use SQL derived names in SpanTraces (#97)
[1.2.5] 2019-12-02
Added:
* Autoclose running spans when request finishes (#93)
* Rate Limit AppServerLoad metadata (#94)
* Add `language_version` key to AppServerLoad metadata (#95)
Fixed:
* Prevent errors if AppServerLoad metadata is not set (#92)

Update CoreAgent version to 1.2.6, with several bug fixes

---

pytest.ini
tests/unit/core/test_util.py

Ref #296. Configure warnings through Pytest's [filterwarnings option](https://docs.pytest.org/en/latest/warnings.html) so if we cause a warning to be raised, the test fails. Also improve octal tests slightly.

Make tests error on any warnings we raise

---

src/scout_apm/compat.py
tests/compat.py
tox.ini

We were doing this inconsistently.  I prefer checking versions as it avoids burying errors. See https://twitter.com/nicoddemus/status/1146196274309414912 .

Use Python version checking for all compat imports

---

CHANGELOG.md

It was only released a day later due to problems getting release to work.

Fix 2.9.0 release date in CHANGELOG

---

src/scout_apm/async_/starlette.py
src/scout_apm/core/web_requests.py
tests/integration/test_starlette_py36plus.py
tests/tools.py

Extracted from #412 whilst it's still in development:
* Move the Starlette-specific ASGI request data tracking into a generic helper `asgi_track_request_data` that should also do a bit less work.
* Move the test function `get_scope()` into a generic test tool `asgi_http_scope()`

Add and use common ASGI helpers

---

tests/integration/test_starlette_py36plus.py

Noticed this `with pytest.raises()` wasn't around a single statement so ambiguous.

Tidy Starlette test

---

.travis.yml

After reviewing the changes to Twine and the slightly panicked changes I made to the Travis config to ship 2.9.0, I think the configuration I ended up with should work on Twine 3.1.1 as well. Fixes #411.
We'll only be able to test on next release.

Use latest twine again

---

CHANGELOG.md
setup.py
src/scout_apm/core/metadata.py

Use importlib.metadata.distributions to determine package versions

---

CHANGELOG.md
src/scout_apm/flask/__init__.py
tests/integration/test_flask.py

This duplicates the information in the Controller span and we don't do it for any of the other integrations.

Remove Flask 'name' tag

---

src/scout_apm/core/socket.py

Fixes #405.
Tested by modifying `StartSpan` to output in valid datetime strings. Saw `NoParse` in the core agent logs, Python socket thread didn't crash.

Ignore unrecognized responses from the core agent

---

pytest.ini
tests/integration/instruments/test_urllib3.py
tox.ini

Fixes #296. Seems there were less third party warnings to chase down than I thought.

Make tests error on any unknown warning

---

CHANGELOG.md
src/scout_apm/instruments/pymongo.py
tests/integration/instruments/test_pymongo.py

These seem to have been initially missed - maybe they weren't implemented in PyMongo at the time. Added a test to detect new methods and make sure we decide whether or not to instrument them.

Track missing PyMongo Collection methods

---

CHANGELOG.md
src/scout_apm/compat.py
src/scout_apm/instruments/elasticsearch.py
tests/integration/instruments/test_elasticsearch.py

Fixes #435. Copying what #436 did for PyMongo.

Add tracking for missing Elasticsearch client methods

---

CHANGELOG.md

Clarify that it's from PyPI. Pip should pick it up but users might miss why there's a new dependency.

CHANGELOG link to importlib-metadata package

---

src/scout_apm/cherrypy.py
tests/integration/test_cherrypy.py

When testing the integration added in #431, I found that the `favicon.ico` route added by `cherrypy.quickstart()` was showing up as "Unknown" controller in the Scout UI. This should fix that.

Track CherryPy static files

---

tests/integration/test_bottle.py
tests/integration/test_cherrypy.py
tests/integration/test_django.py
tests/integration/test_falcon.py
tests/integration/test_flask.py
tests/integration/test_nameko.py
tests/integration/test_pyramid.py
tests/integration/test_starlette_py36plus.py
tests/unit/core/test_web_requests.py

Have continued to see many test failures like:
```
_ test_track_amazon_request_queue_time_valid[Root=1-{start_time}-12456789abcdef012345678] _
header_value = 'Root=1-{start_time}-12456789abcdef012345678'
tracked_request = <TrackedRequest(request_id='req-fe5f34ed-77b0-495d-829a-73f762a81d20', tags={'scout.queue_time_ns': 1999636992})>
@pytest.mark.parametrize(
"header_value",
[
"Root=1-{start_time}-12456789abcdef012345678",
"Root=1-{start_time}-12456789abcdef012345678;CalledFrom=app",
"Self=1-{start_time}-12456789abcdef012345678",
"Self=1-{start_time}-12456789abcdef012345678;Root=1-123-abcdef012345678912345678",  # noqa: E501
"Self=1-{start_time}-12456789abcdef012345678;Root=1-123-abcdef012345678912345678;CalledFrom=app",  # noqa: E501
],
)
def …
```

Fix random queue time failures

---

src/scout_apm/compat.py
tests/integration/test_bottle.py
tests/integration/test_celery.py
tests/integration/test_cherrypy.py
tests/integration/test_django.py
tests/integration/test_dramatiq.py
tests/integration/test_falcon.py
tests/integration/test_flask.py
tests/integration/test_flask_sqlalchemy.py
tests/integration/test_huey.py
tests/integration/test_nameko.py
tests/integration/test_pyramid.py
tests/integration/test_rq.py

This helps reduce confusion especially when there are two config arguments - one for the library and one for Scout.

Make all app_with_scout functions kwargs-only

---

src/scout_apm/core/config.py
tests/unit/core/test_config.py

* Remove `name()` method and instead just use the class names, which have been shortened since they're namespaced enough.
* Remove unnecessary `global` declarations, since we're only mutating the internal state of `SCOUT_PYTHON_VALUES`.

Simplify Config classes

---

tests/unit/core/test_metadata.py

Missed in #430 - the tests passed by removing `pkg_resources` because presumably it's used somewhere under the hood, but best not to rely on that.

Make metadata tests remove correct package name

---

src/scout_apm/core/samplers/thread.py
src/scout_apm/core/threading.py
tests/unit/core/samplers/test_thread.py
tests/unit/core/test_threading.py

This allows the functionality to be tested independently and used elsewhere (in future CoreAgentSocket refactor).

Extract SingletonThread class from SamplersThread

---

src/scout_apm/core/__init__.py
src/scout_apm/core/metadata.py
src/scout_apm/core/samplers/thread.py
src/scout_apm/core/socket.py
src/scout_apm/core/tracked_request.py
tests/integration/core/test_socket.py
tests/unit/core/test_metadata.py

Refactor in order to:
* Use the simpler, tested, idempotent thread logic of `SingletonThread`, extracted from `SamplersThread` in #448.
* Use a shared command queue - commands enqueued while the thread happens to be shutting down will still be sent.
* Provide a simpler interface to users - simply call `send(command)`.
* Avoid `ResourceWarning`s from sockets being left open in tests - they should all be `close()`d now.

Rewrite CoreAgentSocket as a SingletonThread

---

src/scout_apm/core/core_agent_manager.py

As per referenced issue, OSError and IOError are only the same thing on Python 3, but we support Python 2.

Ignore false positive from flake8-bugbear B014

---

CHANGELOG.md
src/scout_apm/compat.py
src/scout_apm/falcon.py
tests/integration/test_falcon.py

Refs #336. Hug uses Falcon for its HTTP API interface. This PR contains some improvements to the Falcon integration that will be helpful for Hug:
* `set_api()` is no longer required, thanks to some stack inspection.
* Tracing is automatically disabled if installation fails, like other intgerations.
* Callable class-based responders are supported. Hug uses one of these.

Improve Falcon integration

---

tests/integration/test_rq.py
tox.ini

It's incompatible with the latest redis-py 3.4.0: https://github.com/jamesls/fakeredis/issues/260
We only used it for a few tests. It's easier to simply use the Redis server we already run during normal tests.

Remove fakeredis

---

.pre-commit-config.yaml

Discovered the pre-commit setup was actually running my globally installed linters.

pre-commit use tox venv

---

CHANGELOG.md
README.md
src/scout_apm/falcon.py
src/scout_apm/hug.py
tests/integration/test_falcon.py
tests/integration/test_hug.py
tox.ini

Fixes #336.
Hug uses Falcon under the hood, so this builds on top of it to provide a Hug integration with a separate interface.

Add Hug integration

---

pytest.ini

PR #429 set the base configuration to "default" which just prints the warnings rather than erroring on them. This fixes that.
However, luckily the printing behaviour showed some warnings still - `ImportWarning`s and `ResourceWarning`s. By default [Python suppresses these](https://docs.python.org/3/library/warnings.html#default-warning-filter) and [Pytest doesn't replace those filters](https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning).
This PR sets the main action to 'error', and specifies extra filters to override the default ones Python configures.

Actually error on warnings

---

CHANGELOG.md
DEVELOPMENT.md
src/scout_apm/compat.py
src/scout_apm/instruments/elasticsearch.py
tests/integration/instruments/test_elasticsearch.py
tests/unit/test_compat.py

Fixes #454. Fixes #456. Work around positional arguments changing order through function inspection. Stop patching scripts_painless_context() since it has been removed with no intention of re-adding.

Fix elasticsearch 7.5.1 issues

---

CHANGELOG.md
src/scout_apm/core/config.py
src/scout_apm/core/core_agent_manager.py
src/scout_apm/falcon.py
tests/integration/core/test_core_agent_manager.py
tests/integration/test_falcon.py
tests/unit/core/test_config.py

This is the recommended way for Python users to track down deprecations/problems in their code. We should have been using it all along.

Convert user warnings from logging.warnings to warnings.warn

---

src/scout_apm/core/tracked_request.py

This method's return value isn't used.

Remove unnecesary 'return 0'

---

CHANGELOG.md
src/scout_apm/core/backtrace.py
tests/unit/core/test_backtrace.py

Copied from the Ruby agent: https://github.com/scoutapp/scout_apm_ruby/blob/84575a57f2fb64bced6f2394632212f2bfb0268f/lib/scout_apm/layer.rb#L116
Not strictly related to implementing the issue, but spotted whilst investigating it as an idea to reduce memory usage and overhead.

Limit traceback size

---

src/scout_apm/core/socket.py
tests/conftest.py
tests/integration/core/test_socket.py

Should prevent random errors which seem to happen fairly frequently in Travis runs like:
```
______________________________ test_launch_error _______________________________
caplog = <_pytest.logging.LogCaptureFixture object at 0x7f44d4c65f60>
core_agent_manager = <scout_apm.core.core_agent_manager.CoreAgentManager object at 0x7f44d4c65940>
def test_launch_error(caplog, core_agent_manager):
caplog.set_level(logging.ERROR)
exception = ValueError("Hello Fail")
with mock.patch(
"scout_apm.core.core_agent_manager.CoreAgentManager.agent_binary",
side_effect=exception,
):
result = core_agent_manager.launch()
assert not result
assert not is_running(core_agent_manager)
>       assert caplog.record_tuples == [
("scout_apm.core.core_agent_manager", logging.ERROR, "Error running Core Agent")
]
E …
```

Stop CoreAgentSocketThread after every test

---

src/scout_apm/bottle.py
tests/integration/test_bottle.py

This brings us in line with the other integrations' "configuration copying" implementations and means that if we drop a key from `known_keys()` it will still apply.

Bottle copy all config keys not just known keys

---

CHANGELOG.md
pytest.ini
setup.py
src/scout_apm/compat.py
src/scout_apm/core/core_agent_manager.py
tests/integration/instruments/test_urllib3.py
tox.ini

Basically avoid using `requests` so that we aren't pulling it in for people who aren't using it. Whilst popular I think some projects will be moving to httpx and it's best to minimize our footprint. We only use it for the single download of the core agent.

Move from requests to urllib3

---

src/scout_apm/core/config.py
tests/unit/core/test_config.py

Fix new value from #474 being set as an environment variable, which will only be a string.

Convert shutdown_timeout_seconds to float

---

CHANGELOG.md
setup.py

Fixes #488.
I tested this by deliberately introducing a syntax error into `_objtrace.c`. Without `optional=True`, installation in a virtual environment failed; with it, it passes, and without any error message.

Make objtrace C extension optional

---

src/scout_apm/core/config.py

Set default app name to "Python App"

---

CHANGELOG.md
src/scout_apm/instruments/elasticsearch.py
src/scout_apm/instruments/jinja2.py
src/scout_apm/instruments/pymongo.py
src/scout_apm/instruments/redis.py
src/scout_apm/instruments/urllib3.py
tests/integration/instruments/test_elasticsearch.py
tests/integration/instruments/test_jinja2.py
tests/integration/instruments/test_jinja2_py36plus.py
tests/integration/instruments/test_pymongo.py
tests/integration/instruments/test_redis.py
tests/integration/instruments/test_urllib3.py

A user was confused around the log messages stating that we failed to import elasticsearch, wondering why Scout depends on it.
This improves the log messages to be at DEBUG level only for attempts to instruments, and rewords them to be a little clearer around the process.

Improve log messages around instrumentation

---

CHANGELOG.md
src/scout_apm/instruments/elasticsearch.py

These methods seem to have been added in version 7.6.0, although that's [not documented](https://github.com/elastic/elasticsearch-py/issues/1168). Our test `test_all_client_attributes_accounted_for` started failing.
These methods don't take an index argument:
```
>>> import elasticsearch
>>> help(elasticsearch.Elasticsearch.get_script_context)
Help on function get_script_context in module elasticsearch.client:
get_script_context(self, params=None, headers=None)
Returns all script contexts.
>>> help(elasticsearch.Elasticsearch.get_script_languages)
Help on function get_script_languages in module elasticsearch.client:
get_script_languages(self, params=None, headers=None)
Returns available script types, languages and contexts
```

Instrument new Elasticsearch methods

---

tox.ini

They released a version that requires `typing`, which is in Python 3.5+ only, without using setuptools to restrict the version to 3.5+.

Fix httpretty install

---

MANIFEST.in

For some reason it has started reporting about the tests not being included. Exclude them.

Fix MANIFEST.in for check-manifest

---

pytest.ini

```
.tox/py27-django111/lib/python2.7/site-packages/rq/job.py:575: in save
connection.hmset(key, self.to_dict(include_meta=include_meta))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = Pipeline<ConnectionPool<Connection<host=localhost,port=6379,db=0>>>, name = 'rq:job:bbe77759-175d-4053-88f4-48d8b45844ce'
mapping = {'created_at': '2020-05-07T09:40:26.578828Z', 'data': 'x\x9ck`\xd2\x88\x90g``(I-.)\xd6\xcb\xcc+IM/J,\xc9\xcc\xcf\xd3\x...0\x9bO\x10\x88', 'description': 'tests.integration.test_rq.hello()', 'enqueued_at': '2020-05-07T09:40:26.578908Z', ...}
def hmset(self, name, mapping):
"""
Set key to value within hash ``name`` …
```

Ignore Redis warning triggered by rq

---

.travis.yml

Fix some warnings seen in "Build config validation" on [a recent build](https://travis-ci.org/github/scoutapp/scout_apm_python/builds/684191778/config):
* root: deprecated key sudo (The key `sudo` has no effect anymore.)
* root: missing os, using the default linux
* services: value redis-server is an alias for redis, using redis

Fix Travis config warnings

---

tox.ini

Version 4.4.4 is missing a dependency in install_requires, so ignore it. See https://github.com/celery/celery/issues/6153 .

Fix Celery in tests

---

src/scout_apm/instruments/elasticsearch.py

This new method has appeared, it seems it would be worth instrumenting in case it takes a noticeable amount of time to close the connection.

Instrument Elasticsearch.close()

---

pytest.ini

The 3.0 release added this warning on import under Python 2, crashing tests:
```
__ ERROR collecting tests/integration/test_nameko.py ___
tests/integration/test_nameko.py:8: in <module>
from nameko.containers import get_container_cls
...
.tox/py27-django18/lib/python2.7/site-packages/OpenSSL/crypto.py:12: in <module>
from cryptography import x509
.tox/py27-django18/lib/python2.7/site-packages/cryptography/__init__.py:39: in <module>
CryptographyDeprecationWarning,
E   CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
```

Ignore cryptography's warning about Python 2 EOL

---

MANIFEST.in
pyproject.toml

Declare Python 2.7 compatible output for Black and allow PEP517 builds.

Add pyproject.toml

---

CHANGELOG.md
src/scout_apm/core/config.py

Otherwise `export SCOUT_COLLECT_REMOTE_IP=false` comes in as the string `"false"` which is truthy.

Always convert collect_remote_ip to a boolean

---

CHANGELOG.md
src/scout_apm/django/middleware.py
tests/integration/django_app.py
tests/integration/test_django.py

Django - only track current user when application accessed request.user

---

src/scout_apm/compat.py
src/scout_apm/core/core_agent_manager.py
tests/unit/core/test_core_agent_manager.py

Don't log a full exception when the manifest file is missing, which is the default on a new system. Most users won't use debug-level logs, but when they do we don't want to scare them with a stacktrace for an expected exception.

Simplify and fully test core agent manifest parsing

---

CHANGELOG.md
src/scout_apm/core/config.py
src/scout_apm/core/core_agent_manager.py
src/scout_apm/core/socket.py
tests/compat.py
tests/conftest.py
tests/integration/core/test_core_agent_manager.py
tests/integration/core/test_socket.py
tests/unit/core/test_core_agent_manager.py

Fixes #553.
Because the `probe` and `shutdown` core-agent commands don't work with TCP mode, this moves the relevant test functions to instead check for the process, and terminate it for shutdown.

Connect to core agent over TCP by default

---

src/scout_apm/core/agent/socket.py

Previously a failed connection would count as a success, and the thread would continue to try registering, which failed with a `BrokenPipeError`:
```
2020-09-03T16:38:38+0100 DEBUG CoreAgentSocketThread connection error: OSError(22, 'Invalid argument')
Traceback (most recent call last):
File "/.../scout_apm_python/src/scout_apm/core/agent/socket.py", line 178, in _connect
self.socket.connect(self.get_socket_address())
OSError: [Errno 22] Invalid argument
2020-09-03T16:38:38+0100 INFO Registering with app=Test Django App key_prefix=... key_format_validated=True host=None
2020-09-03T16:38:38+0100 DEBUG CoreAgentSocketThread exception on _send: BrokenPipeError(32, 'Broken pipe') on PID: 95487 on thread: <CoreAgentSocketThread(Thread-1, started daemon 123145577099264)>
Traceback (most recent …
```

Raise exception on final connect attempt

---

.github/workflows/release.yml
setup.py

This version of cibuildwheel has disabled our extensionless wheel building since it sees that it's not a binary wheel and says to build it once yourself (see below logs). This PR does that by installing Python 2.7 on GitHub Actions and disabling all extensionless wheel building happening in cibuildwheel.
It also upgrades to using Python 3.8 for the build process.
```
Building wheels for collected packages: scout-apm
Building wheel for scout-apm (PEP 517): started
Building wheel for scout-apm (PEP 517): finished with status 'done'
Created wheel for scout-apm: filename=scout_apm-2.16.0-py2-none-any.whl size=58254 sha256=f46f3bcd3b2100b905a05a8f3cfe89359eb97a6877e04bf5b0ea5114e0b1c904
Stored in directory: /tmp/pip-ephem-wheel-cache-2UXuaG/wheels/ca/c1/c0/18849572a9d9850c185240b5123a2c0efd5387 …
```

Fix release process for cibuildwheel 1.6.0

---

.github/workflows/release.yml

Refs #581. We shouldn't push a wheel until it's released.

Disable Python 3.9 wheels

---

.github/workflows/release.yml

cibuildwheel just added support for this, however it fails for us since our wheels are pure Python, on PyPy:
```
You should consider upgrading via the '/opt/pypy/pypy3.7-7.3.2/bin/pypy -m pip install --upgrade pip' command.
Processing /project
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing wheel metadata: started
Preparing wheel metadata: finished with status 'done'
Building wheels for collected packages: scout-apm
Building wheel for scout-apm (PEP 517): started
Building wheel for scout-apm (PEP 517): finished with status 'done'
Created wheel for scout-apm: filename=scout_apm-2.16.2-py3-none-any.whl size=60196 …
```

Disable building PyPy 3.7 wheels

---

tox.ini

The latest 3.12 series doesn't support Django 1.11.

Pin Django 1.11 DRF version

---

.github/workflows/release.yml

This should stop this deprecation warning: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
We only pinned to a specific patch version since we needed the version that supported installing the latest Python. That's now been released onto the main `v2` tag/branch.

Use latest GitHub Actions setup-python

---

src/scout_apm/core/web_requests.py
tests/unit/core/test_web_requests.py

Occassionally Amazon will send the time string in hexidecimal format.
It's not parseable in the format, but they do indicate it will be 8
characters long. It should be reasonable that decimal format time strings
will be longer than that.

Support hexidecimal amazon time strings.

---

pytest.ini

Update the ignore from 30d0854f4732fe361be3f0fcf0469f94626532da to target the triggering module, and correct the comment since it's nothing to do with Django.

Improve ignoring of eventlet warning

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
MANIFEST.in
src/scout_apm/core/config.py
tests/unit/core/test_web_requests.py
tox.ini

This is easier to manage and `pre-commit autoupdate` can keep dependencies up to date.

Move to vanilla pre-commit

---

tox.ini

'false' is the default so no need to specify: https://tox.readthedocs.io/en/latest/config.html#conf-usedevelop

Remove 'usedevelop' from tox.ini

---

tox.ini

This isn't needed since the move from Travis to GitHub Actions.

Drop unused test depednency pytest-travis-fold

---

tests/integration/test_nameko.py
tox.ini

This is only to get the build green so we can release. I think we will need to split the nameko tests out to their own tox environment to avoid such conflicts - which implies splitting each integration into its own tox environment.

Temporarily disable nameko tests

---

CHANGELOG.md
src/scout_apm/core/agent/manager.py

Detected by latest pytest feature of failing tests on "unraisable exceptions", from our warnings config that turns the `ResourceWarning` into an exception.

Fix socket resource leak in CoreAgentDownloader

---

tests/integration/instruments/test_elasticsearch.py

Detected by latest pytest feature of failing tests on "unraisable exceptions", from our warnings config that turns the ResourceWarning into an exception.

Fix resource leak in elasticsearch tests

---

.github/workflows/release.yml
CHANGELOG.md

Also undo removal from Python 3.5 which shouldn't be necessary.

Build wheel on Python 3.9

---

.github/workflows/release.yml
CHANGELOG.md

Also run cibuildwheel with Python 3.9 since it's now stable.

Build wheels for ARM on Linux

---

CHANGELOG.md
setup.py
src/scout_apm/django/__init__.py
tox.ini

Requires cleanup of removing >=3.2rc1 in tox after 3.2 is released.

Add support for django 3.2.

---

tests/unit/core/test_web_requests.py

There's some floating point rounding errors here. Subtracting
some time to ensure the header time is before the tracked
request start time seems to fix it.
Related to #328
Reproduced using pytest-repeat plugin and a count of 1000.

Fix timing rounding bug in tests.

---

CHANGELOG.md
src/scout_apm/api/__init__.py
src/scout_apm/async_/api.py
src/scout_apm/async_/starlette.py
src/scout_apm/compat.py
src/scout_apm/core/context.py
src/scout_apm/instruments/__init__.py
src/scout_apm/instruments/asyncio.py
tests/integration/instruments/test_asyncio_py36plus.py
tests/integration/test_api_py36plus.py

Passes the tracked request via an attribute on the current task for LocalContext to use.
Only instruments basic coroutines and tasks.
Closes scoutapp/scout_apm_python#469

Instrument asyncio for python 3.6+

---

tox.ini

jinja2 v3 introduced changes for async_render which impacts render.
These will take more effort than we have available at the moment.
This will be addressed as a part of #646.

Pin jinja2 support to v2.x temporarily. 

---

CHANGELOG.md
src/scout_apm/bottle.py
src/scout_apm/cherrypy.py
src/scout_apm/core/web_requests.py
src/scout_apm/django/middleware.py
src/scout_apm/falcon.py
src/scout_apm/pyramid.py
tests/integration/test_bottle.py
tests/integration/test_cherrypy.py
tests/integration/test_django.py
tests/integration/test_falcon.py
tests/integration/test_flask.py
tests/integration/test_nameko.py
tests/integration/test_pyramid.py
tests/integration/test_starlette_py36plus.py
tests/unit/core/test_web_requests.py

The header's time value is in seconds which isn't enough precision
for us to provide quality data to users. With seconds precision, the
queue time hovers about 0.5s due to the truncation.
It may be possible to pull the millisecond precision data from the
AWS logs themselves and avoid the python agent altogether.
Closes #631

Remove tracking queue time from amazon trace id header.

---

CHANGELOG.md
src/scout_apm/celery.py
tests/integration/test_celery.py

As of Celery 5.1.0, the delivery info for tasks includes default
values of None rather than no key.

Include Celery's priority and fix failing tests.

---

CHANGELOG.md
src/scout_apm/core/tracked_request.py
tests/unit/core/test_tracked_request.py

It now contains summary information for the request that is
logged after the request has been sent.
Closes #654

Improved debug logging for requests.

---

CHANGELOG.md
setup.py

PyPI treats the string as an array and is making each
character a keyword.

Supply a list of keywords rather than a string.

---

CHANGELOG.md
setup.py
src/scout_apm/api/__init__.py
src/scout_apm/celery.py
src/scout_apm/compat.py
src/scout_apm/core/__init__.py
src/scout_apm/core/backtrace.py
src/scout_apm/core/config.py
src/scout_apm/core/error.py
src/scout_apm/core/error_service.py
src/scout_apm/core/tracked_request.py
src/scout_apm/core/web_requests.py
src/scout_apm/django/apps.py
src/scout_apm/django/middleware.py
src/scout_apm/django/request.py
src/scout_apm/instruments/urllib3.py
tests/compat.py
tests/conftest.py
tests/integration/core/agent/test_socket.py
tests/integration/core/test_error_service.py
tests/integration/django_app.py
tests/integration/instruments/test_urllib3.py
tests/integration/test_api.py
tests/integration/test_celery.py
tests/integration/test_django.py
tests/unit/core/test_backtrace.py
tests/unit/core/test_error.py
tests/unit/core/test_web_requests.py

Monitor errors via got_request_exception signal.
The middleware process_exception would only allow us to track
exceptions thrown in views, that weren't picked up by an
earlier middleware that returned a result. This solution allows
us to track exceptions that occur anywhere in the application.
The downside to this is that it's possible if another receiver
of got_request_exception throws a new exception, our handler
may get the wrong exception with sys.exc_info().
We could limit the scope of that issue by injecting a middleware
that's as far down the list as possible to wrap the view
and catch exceptions there. Then rely on the signal handler
for catching exceptions in the middleware.
Create ErrorServiceThread to buffer error messages.
TODO:

Error monitoring

---

CHANGELOG.md
src/scout_apm/core/backtrace.py
tests/unit/core/test_backtrace.py

A namespace package does not have a file property. Instead utilize
the __path__ attribute and use the first element in the list. While
this may not capture the dynamic cases, it should capture the
necessary data for most cases.
Fixes #667

Handle case of namespace packages when capturing backtraces.

---

.github/workflows/release.yml

I suspect we'll need to break up the release process to use both versions
of cibuildwheels to build binaries for all versions of python.
References #584

Pin cibuildwheels to < 2 to support building binaries for python3.5.

---

CHANGELOG.md
src/scout_apm/core/backtrace.py
tests/unit/core/test_backtrace.py

Skip handling _NamespacePath for now as it's an inner class for importlib.
Closes #691

Make module_filepath more robust for unexpected results.

---

tests/unit/core/samplers/test_thread.py

Occasionally the core agent thread logs after the samplers thread
logs the message we're looking for. This is still a valid case as
it's a race condition.

Improve robustness of test_ensured_stopped.

---

.github/workflows/main.yml
CHANGELOG.md

We need to use Ubuntu 18 to support python3.4 and Ubuntu20 to support
modern versions.

Split CI test github actions into two jobs.

---

tox.ini

CherryPy dropped support for python 3.5 in 18.6.1
more-itertools started using non-compatible python 3.5 syntax
in 8.11.0 and is used by CherryPy.

Fix the build for python3.5 and cherrypy usage.

---

tox.ini

Added to silence the following warning from redis-py:
UserWarning: redis-py works best with hiredis. Please consider installing

Add hiredis parser for tests.

---

CHANGELOG.md
src/scout_apm/instruments/pymongo.py
tests/integration/instruments/test_pymongo.py

Avoid instrumenting PyMongo collection methods that were removed in v4.

---

CHANGELOG.md
src/scout_apm/celery.py
tests/integration/test_celery.py

Celery doesn't always send a stack trace object to the
task_failure handlers. In those cases, it sends a string.
Rather than parse the string, fallback to the einfo
instance to access the traceback.
Fixes #708

Fallback to celery task_failure einfo param.

---

CHANGELOG.md
setup.py
src/scout_apm/compat.py
src/scout_apm/core/error_service.py
src/scout_apm/django/apps.py
src/scout_apm/flask/__init__.py
tests/compat.py
tests/conftest.py
tests/integration/core/test_error_service.py
tests/integration/test_django.py
tests/integration/test_flask.py
tests/unit/core/test_error.py
tox.ini

Removes requests from packages dependencies
Requires integration testing to confirm error logging still works properly.

Use urllib3 to post error messages to Scout Error API. 

---

CHANGELOG.md
src/scout_apm/instruments/elasticsearch.py
tests/integration/instruments/test_elasticsearch.py

Only log warnings for ElasticSearch client method instrumentation
if no client methods were instrumented. Otherwise, log the issues at
the debug level. This avoids flooding logs when clients use an older
version of ElasticSearch.
Fixes #713

Log elasticsearch client method instrumentation problems at DEBUG.

---

.github/workflows/main.yml
tox.ini

Auto is the library's recommended default. When the scout agent
needs to support Trio, we'll need to switch to strict.

Set pytest asyncio mode to auto.

---

.github/workflows/release.yml
CHANGELOG.md

* Upload all builds to Test PyPI
* Rework release Github action to utilize newer versions of cibuildwheel when available.
* Avoid supplying earlier versions of python to cibuildwheel > 2.
* Supply the various manylinux images.
* Break the two cibuildwheel configurations into two via a matrix, except py3.10 for manylinux1
* Specify AArch64 manylinux image.
* Only build aarch64 wheels when using a viable manylinux image.
For some reason, a manylinux2014 image is still used even when manylinux_2_24 is specified

Build wheels for all versions of python.

---

tox.ini

The current python agent doesn't support Elasticsearch 8+.
The issue to instrument that is #725

Stabilize build for Elasticsearch < 8.0.0

---

CHANGELOG.md
src/scout_apm/celery.py

I think finding the underlying issue (it's possible it's not from `scout_apm_python` but one in my control) is important, but I think that the instrumentation itself shouldn't raise.
Find to close this if you have a better solution / idea for handling this.
Resolves #731

celery: Skip tagging `delivery_info` if missing from request

---

CHANGELOG.md
src/scout_apm/core/backtrace.py
src/scout_apm/core/error.py
src/scout_apm/core/tracked_request.py
tests/unit/core/test_backtrace.py
tests/unit/core/test_error.py

The core-agent requires the full path as it will do filtering based
on the scout settings itself. However, the error service needs to do
the filtering and file path manipulation itself. The error service
needs to prepend the scm_directory value, if it exists, to the file
paths.
Fixes #723

Support full and relative file paths in traces.

---

CHANGELOG.md
src/scout_apm/core/__init__.py
src/scout_apm/core/backtrace.py
tests/unit/core/test_backtrace.py

When a frame of the stack is from an eval call, there
is no module.

Always return a tuple from backtrace.filepaths.

---

.github/workflows/main.yml
CHANGELOG.md
DEVELOPMENT.md
src/scout_apm/instruments/elasticsearch.py
tests/integration/instruments/test_elasticsearch.py
tox.ini

Transport was moved to elastic_transport. Check there first
and fallback to elasticsearch if it's not there.
Updates the development docs to contain instructions on running
elasticsearch v8.
Closes #725

Update elasticsearch testing for v8.

---

setup.py

pyOpenSSL and urllib3[secure] are deprecated in the upcoming release (1.26.12)
https://github.com/urllib3/urllib3/issues/2680
Removed 'urllib3[secure] < 1.25 ; python_version < "3.5"' and  'urllib3[secure] < 2 ; python_version >= "3.5"'
Closes #746

Deprecation notice about urllib3[secure]

---

pytest.ini
src/scout_apm/celery.py
tests/conftest.py
tests/unit/core/test_objtrace.py
tox.ini

This PR adds py311 to tox environments and fixes a couple small issues.
- Test fixture to mock `ErrorServiceThread.send`. For some reason in 3.11, the return type of the wrapper wasn't callable, so invoking `ErrorServiceThread.send` threw `AttributeError: 'method' object has no attribute __get__`. This fix is backwards compatible and works with previous python versions.
- Similar to <py35, in py311 you can't force memory reallocations, so the conditional skip for that test was updated to skip >=3.11.

764 update agent to fully support python 311

---

.github/workflows/main.yml
.pre-commit-config.yaml
CHANGELOG.md
DEVELOPMENT.md
pytest.ini
src/scout_apm/core/config.py
src/scout_apm/falcon.py
src/scout_apm/flask/sqlalchemy.py
src/scout_apm/instruments/elasticsearch.py
tests/integration/test_flask_sqlalchemy.py
tests/integration/test_rq.py
tox.ini

This makes a number of changes to the application, though mainly to the tests to restore CI tests. 2.7 and 3.4 are going to continue to fail. Those environments are becoming more and more difficult to maintain as vendors drop support.
- Fix CI for python 2.7, 3.4, 3.5, 3.6, 3.8
- Update ElasticSearch support for 8.7.0 (``health_check``).
- Support flask_sqlalchemy v3. This requires a integration change where ``instrument_sqlalchemy`` is called before ``db.init_app()``.
- Disable tests for SQLAlchemy v2 to allow CI tests to pass.

Resolve CI errors

---

src/scout_apm/celery.py
src/scout_apm/compat.py
src/scout_apm/core/agent/manager.py
src/scout_apm/core/agent/socket.py
src/scout_apm/core/backtrace.py
src/scout_apm/core/config.py
src/scout_apm/core/error.py
src/scout_apm/core/metadata.py
src/scout_apm/core/web_requests.py
src/scout_apm/django/request.py
src/scout_apm/instruments/urllib3.py
tests/compat.py
tests/integration/instruments/test_asyncio_py36plus.py
tests/integration/instruments/test_elasticsearch.py
tests/integration/test_celery.py
tests/integration/test_django.py
tests/integration/test_rq.py
tests/tools.py
tests/unit/core/agent/test_manager.py
tests/unit/core/test_config.py
tests/unit/core/test_metadata.py
tests/unit/core/test_platform_detection.py
tests/unit/core/test_tracked_request.py
tests/unit/test_compat.py

As we only support Py3.8+ in the coming version of the agent, there is no need for all of these version checks in the code.

remove in-code python version checks

---

DEVELOPMENT.md
setup.py
src/scout_apm/instruments/urllib3.py

This PR updates urllib3 instrumentation to handle version >= 2 and removes the limit requirement. 
urllib3[secure] is being deprecated(see [here](https://github.com/urllib3/urllib3/issues/2680)), however we still need `certifi` so is is now specified in the dependencies.

Handle newer urllib3

---

.github/workflows/release.yml

We were seeing warnings in github actions from using outdated versions. 
This bumps versions to latest major release.

update release action versions

---

.github/workflows/main.yml
.github/workflows/release.yml
.gitignore
pytest.ini
setup.py
tests/integration/test_falcon.py
tox.ini

- add build for python 3.12
- add tox env for python 3.12 
- add tox env for django5 pre release. Django 5 only supports python >3.10. 
- add warning ignores to pytest config for new deprecation warnings (from dependencies) in python 3.12. 
- removes assertion of recwarn length in falcon tests due to new deprecation warnings in tests.

Python 3.12 support

---

CHANGELOG.md
src/scout_apm/core/agent/manager.py
src/scout_apm/core/platform_detection.py
src/scout_apm/core/tracked_request.py

- Alias "arm64" to "aarch64" to use existing overrides/builds
- Add a hint that core agent download failed http response check

Mac OS platform handling

---

CHANGELOG.md
setup.py
tests/integration/instruments/test_urllib3.py

- Bump version
- Update Changelog
- Remove invalid urllib3 attr test
- This was obviated by some version-checking code in the instrumentation

Prep 3.0.2 Release

---

src/scout_apm/bottle.py
src/scout_apm/celery.py
src/scout_apm/core/queue_time.py
src/scout_apm/core/web_requests.py
src/scout_apm/django/middleware.py
src/scout_apm/falcon.py
tests/integration/test_celery.py
tests/unit/core/test_queue_time.py
tests/unit/core/test_web_requests.py

This will update the queue time tracking value for background jobs to be in nano seconds, similar to that of web requests.
Moves the tracking of queue time & latency, and supporting conversions, to a new module.
Update queue time / latency tag for Celery workers from `queue_time` to `scout.job_queue_time_ns`

Convert background job queue time / latency to nano seconds

---

src/scout_apm/core/config.py
tests/conftest.py

Updates the core agent version to use 1.5.0.
Changes to the core-agent include flushing batched payloads on receiving of termination signals, capturing latency and allocation metrics for background jobs, as well as a few changes to the exit codes of the core agent.
This core agent docs will also be updated and can be found here:
https://scoutapm.com/docs/core-agent
With updates to the core-agent, now flushing payloads on a couple signals, we need to wait for the process to terminate in the tests.

Update core-agent version to 1.5.0

---

src/scout_apm/core/agent/manager.py
tests/integration/core/agent/test_manager.py

Will check for an already running exit code when launching the core agent. As many processes may try and start the core agent at a similar time, exception logs would be thrown even though the launch of the single core agent instance was successful.

Check for already running status code when launching core agent.

---

setup.py
src/scout_apm/api/__init__.py
src/scout_apm/celery.py
src/scout_apm/dramatiq.py
src/scout_apm/huey.py
src/scout_apm/rq.py
tests/integration/test_api.py
tests/integration/test_celery.py
tests/integration/test_dramatiq.py
tests/integration/test_huey.py
tests/integration/test_rq.py

- Sets `TrackedRequest.operation` attribute when we create the `Job/` spans in the integrations. 
- This will facilitate linking Jobs back to relevant logs in Scout.

Set operation for Job spans

---

src/scout_apm/core/config.py
src/scout_apm/core/web_requests.py
tests/integration/test_celery.py
tests/unit/core/test_config.py
tests/unit/core/test_sampler.py

- Allows users to pass sampling configuration that includes leading slashes. 
- Strips these leading slashes in the config module.

Strip leading slashes for sampling config

---

.github/workflows/main.yml
.github/workflows/release.yml
setup.py
src/scout_apm/rq.py
tests/integration/core/test_error_service.py
tests/integration/instruments/test_urllib3.py
tox.ini

- Replaced httpretty with python-mocket
- httpretty had gone unmaintained
- Squelched some socket-not-closed warnings; looks like internal library handling and the semantics of our agent haven't changed around urllib `PoolManager`
- Updated upload/download-artifact to new v4/non-deprecated versions
- Manually name and differentiate artifacts within the run to avoid collision
- update setup-python and checkout action versions
- Remove deprecated `ubuntu-20.04` runners
- Fix `rq` instrument to handle timezone-aware processing within the lib (🎉 )
- Removed EOL python 3.8 tests
- Created issues to verify Django 5.1/5.2, Elasticsearch 9 and python 3.13 as follow-up

Unpin urllib3
